### ISSUE TITLE
Modal footer color seems odd

### ISSUE THREAD

**Issue by ganeshsomasundaram-okta** [okta/odyssey#116]
On the last step of the wizard completion, the modal footer color seems off
![image](https://user-images.githubusercontent.com/40774045/60913183-b67e2000-a23b-11e9-96e4-eca0319100f8.png)

One more example:
![image](https://user-images.githubusercontent.com/40774045/60914355-39a07580-a23e-11e9-81c2-88cbbcb1feb8.png)

**Comment by edburyenegren-okta** [comment]
This color comes from:

```.o-form-button-bar,
.o-form-toolbar,
.o-form-toolbar.ui-tabs {
  margin-top: -1px;
  padding: 16px;
  border-width: 1px;
  border-style: solid;
  border-radius: 0 0 3px 3px;
  border-color: $gainsboro $gainsboro-2;
  background: $component-bg-color-dark;
  box-shadow: 0 1px 1px rgba(175, 175, 175, 0.16);
  text-align: right;
}
```

`$component-bg-color-dark` is set to `$white-smoke-3`.

`$white-smoke-3` is normally `#f2f2f2`; under DS Theme it maps to `#d1d1d1`.

**Comment by joejezowski-okta** [comment]
re-map to $gray-0 (#FAFAFA)

**Comment by joejezowski-okta** [comment]
@edburyenegren-okta the `box-shadow` attribute doesn't seem accurate. No way it's 0 1px 1px. Looks larger than that. 

Is it getting shadow from somewhere else? Reason I ask is because I need to see how $gray-0 reads.

**Comment by edburyenegren-okta** [comment]
@joejezowski-okta the `box-shadow` listed here is only for the footer bar, not the modal itself

**Comment by joejezowski-okta** [comment]
@edburyenegren-okta hmm…it looks even all the way around the modal.

**Comment by edburyenegren-okta** [comment]
@joejezowski-okta yeah, it's only a pixel deep, so it gets... overshadowed by the modal's `box-shadow`

**Comment by edburyenegren-okta** [comment]
<img width="680" alt="Screenshot 2019-07-16 13 21 51" src="https://user-images.githubusercontent.com/36284167/61326941-b7c7c380-a7cc-11e9-9b76-77d4e2ce1594.png">

@joejezowski-okta Here's `$white-smoke-3` to `cv('gray', '000')`. Unless we want to add a `gray, 100` right now, this looks solid to me?

**Comment by joejezowski-okta** [comment]
@edburyenegren-okta I think this is good man!
