### ISSUE TITLE
[Datalist] Header border is not there

### ISSUE THREAD

**Issue by rajaguruduraisamy-okta** [okta/odyssey#117]
## Detailed description
No divider for headers

> Is this issue related to a specific component?

> What did you expect to happen? What happened instead?

> What browser & version are you experiencing this in?

## Steps to reproduce the issue

1. Step one.
2. Step two.
3. ???
4. Profit.

## Screenshots
Non - DS
<img width="613" alt="Screen Shot 2019-07-09 at 11 23 10 AM" src="https://user-images.githubusercontent.com/29963503/60913323-fe04ac00-a23b-11e9-9002-6fabae89c181.png">

DS
<img width="617" alt="Screen Shot 2019-07-09 at 11 23 17 AM" src="https://user-images.githubusercontent.com/29963503/60913337-06f57d80-a23c-11e9-8e6b-2bb439eb3cca.png">

Please include screenshots to help illuminate the issue.

**Comment by edburyenegren-okta** [comment]
These colors come from:

```.data-list-table {
  th {
    border-right: 1px solid $border-color-default;
    border-bottom: 1px solid $border-bottom-color-default;
    background: $white-smoke-3;
  }

[...]

  td {
    border-right: 1px solid transparent;
    border-bottom: 1px solid $border-color-light;
  }
}
```

`$border-color-default` is set to `$gainsboro-2`
`$gainsboro-2` is normally `#dddddd`; it has been remapped to `#d1d1d1`

`$border-bottom-color-default` is set to `$gainsboro`
`$gainsboro` is normally `#dadada`; it has been remapped to `#d1d1d1`

`$white-smoke-3` is normally `#f2f2f2`; it has been remapped to `#d1d1d1`

**Comment by joejezowski-okta** [comment]
@edburyenegren-okta `$white-smoke-3` should go to `$gray-0`.

As for the strokes, I'm thinking we might need something in between and make a Gray 100. Thoughts @nickarcidy-okta?

**Comment by edburyenegren-okta** [comment]
@joejezowski-okta you mean `$white-smoke-3` set to `cv('gray', '000')`?

**Comment by edburyenegren-okta** [comment]
<img width="939" alt="Screenshot 2019-07-16 13 27 15" src="https://user-images.githubusercontent.com/36284167/61327291-74218980-a7cd-11e9-8fa6-886bca061cd3.png">

@joejezowski-okta Here's $white-smoke-3 to cv('gray', '000'). Unless we want to add a gray, 100 right now, this looks solid to me.

**Comment by joejezowski-okta** [comment]
@edburyenegren-okta the header looks good. Just to call out…it appears that the table column has been turned to white. You have to look closely, but it's there. Not sure if you could fix that here or not.

**Comment by joejezowski-okta** [comment]
Followed up with Edbury. Issue stated above didn't result from our change.
