### ISSUE TITLE
[Form] Hover state introduces different border color for few input components

### ISSUE THREAD

**Issue by rajaguruduraisamy-okta** [okta/odyssey#119]
## Detailed description

1) Checkbox, selectbox hoverstate introduce dark black color border as opposed to other input  components dont have different border color

> Is this issue related to a specific component?

> What did you expect to happen? What happened instead?

> What browser & version are you experiencing this in?

## Steps to reproduce the issue

1. Step one.
2. Step two.
3. ???
4. Profit.

## Screenshots

Please include screenshots to help illuminate the issue.

**Comment by edburyenegren-okta** [comment]
This is the current behavior as well (based on Skylab testing). Seems to be a sprite, not a border color?
