### ISSUE TITLE
[Form] Password eye icon is in different color

### ISSUE THREAD

**Issue by rajaguruduraisamy-okta** [okta/odyssey#121]
## Detailed description
Password eye icon is dark black compared to other icons

> Is this issue related to a specific component?

> What did you expect to happen? What happened instead?

> What browser & version are you experiencing this in?

## Steps to reproduce the issue

1. Step one.
2. Step two.
3. ???
4. Profit.

## Screenshots
<img width="571" alt="Screen Shot 2019-07-09 at 11 30 46 AM" src="https://user-images.githubusercontent.com/29963503/60913842-1f19cc80-a23d-11e9-9b42-4067b3f8ffcb.png">

Please include screenshots to help illuminate the issue.

**Comment by edburyenegren-okta** [comment]
The eye comes from:

```.visibility-16::before {
  content: $visibility;
  color: $icon-color-dark;
}

.visibility-off-16::before {
  content: $visibility-off;
  color: $icon-color-dark;
}
```

The lock comes from:

```.remote-lock-16::before {
  content: $lock;
  color: $icon-color-dark;
}
```

The question mark comes from:

```.form-help-16::before {
  content: $cir-help;
  color: $icon-color-light;
}
```

Based on the Sass, these aren't intended to have the same color:

```$icon-color-dark: $dim-gray-2;
$icon-color-light: $dark-gray-2;
```

Skylab seems to have the same thing:

<img width="1552" alt="Screenshot 2019-07-11 17 55 03" src="https://user-images.githubusercontent.com/36284167/61094712-17a51f80-a405-11e9-835b-c69e0f51576b.png">

@joejezowski-okta how you wanna proceed on this one?

**Comment by joejezowski-okta** [comment]
Let's do icons at `$gray-400`. Contrast ratio is 4.48. Should be very legible to everyone from an a11y perspective.

For the background in the footer, let's follow the other suggestions in the other issues and go to `$gray-0`

**Comment by edburyenegren-okta** [comment]
@joejezowski-okta These icons are different colors in the current UI (see my screenshot).

IMO we shouldn't treat this as a bug and should revisit when we tackle icons. Thoughts?

**Comment by joejezowski-okta** [comment]
@edburyenegren-okta Totally agree. So did Raj submit this thinking it was an issue and it appeared inconsistent?
