### ISSUE TITLE
Datalist Sidebar styling issues

### ISSUE THREAD

**Issue by rchild-okta** [okta/odyssey#122]
Example:
http://0.0.0.0:3000/dataList/datalist-with-filter

- No hoverstate when mousing over sidebar items

**Comment by edburyenegren-okta** [comment]
<img width="943" alt="Screenshot 2019-07-16 13 28 17" src="https://user-images.githubusercontent.com/36284167/61327382-a03d0a80-a7cd-11e9-86e7-50f484463dd9.png">

@joejezowski-okta Here's $white-smoke-3 to cv('gray', '000'). Solves the sidebar background issue; `:hover` color seems a little dark, but maybe not a problem?

**Comment by joejezowski-okta** [comment]
Same as #117 …remapped color looks good. We should fix column border color.

**Comment by joejezowski-okta** [comment]
Followed up with Edbury. Issue stated above didn't result from our change.
