### ISSUE TITLE
Red color for errors looks much brighter

### ISSUE THREAD

**Issue by ganeshsomasundaram-okta** [okta/odyssey#123]
![image](https://user-images.githubusercontent.com/40774045/60914046-8cc5f880-a23d-11e9-83df-9c384c0e29db.png)

![image](https://user-images.githubusercontent.com/40774045/60914636-c77c6080-a23e-11e9-87c0-69c4781c7457.png)

**Comment by edburyenegren-okta** [comment]
@joejezowski-okta thoughts on this one?

**Comment by joejezowski-okta** [comment]
@edburyenegren-okta is this mapped to "Mid Red"?

**Comment by edburyenegren-okta** [comment]
@joejezowski-okta yup, this is `cv('red', 'base')`, but the gradient is programmatically generated by darkening it for the second stop.

**Comment by joejezowski-okta** [comment]
@edburyenegren-okta I'm concerned if we use the lighter red that any other element without a gradient will be too light. My two cents says leave it and we'll solve the issue when we get to buttons someday.

**Comment by edburyenegren-okta** [comment]
@joejezowski-okta works for me - we may also remap the base red for other reasons. This is definitely different, but doesn't seem like a bug.
