### ISSUE TITLE
DataList toolbar styling issues

### ISSUE THREAD

**Issue by rchild-okta** [okta/odyssey#125]
Example:
http://courage.oktaskylab.com/dataList/datalist-with-search-and-icons

A datalist with a toolbar looks a little strange because there's no border between the toolbar (i.e. buttons, search) and the header items.

**Comment by edburyenegren-okta** [comment]
<img width="945" alt="Screenshot 2019-07-16 13 30 17" src="https://user-images.githubusercontent.com/36284167/61327484-df6b5b80-a7cd-11e9-9434-80526ae1c6f5.png">

@joejezowski-okta Here's $white-smoke-3 to cv('gray', '000')

**Comment by joejezowski-okta** [comment]
Looks good.
