### ISSUE TITLE
Header color

### ISSUE THREAD

**Issue by joejezowski-okta** [okta/odyssey#128]
## Detailed description

There is a thin bar at the top of the navigation when logged in that is darker than the main navigation…It maps to the base blue instead of the darker blue.

> Is this issue related to a specific component?

Main navigation/header

> What did you expect to happen? What happened instead?

There should be two blues, there is only one

> What browser & version are you experiencing this in?

Chrome, Version 71.0.3578.98

## Steps to reproduce the issue

1. Log in

## Screenshots

Please include screenshots to help illuminate the issue.

<img width="1034" alt="Screen Shot 2019-07-09 at 11 39 07 AM" src="https://user-images.githubusercontent.com/49886075/60914516-85531f00-a23e-11e9-809d-cc4eeb9de8f0.png">
<img width="1091" alt="Screen Shot 2019-07-09 at 11 39 01 AM" src="https://user-images.githubusercontent.com/49886075/60914517-85ebb580-a23e-11e9-8643-ba3390852620.png">

**Comment by edburyenegren-okta** [comment]
IMO we shouldn't be collecting any of these non-Courage bugs until we wrap up remappings to address those.

**Comment by edburyenegren-okta** [comment]
Non-Odyssey, closing.
