### ISSUE TITLE
[Form] Border color is off for Text select component

### ISSUE THREAD

**Issue by rajaguruduraisamy-okta** [okta/odyssey#129]
## Detailed description
See screenshot 
/modal/multi-view-modal

> Is this issue related to a specific component?

> What did you expect to happen? What happened instead?

> What browser & version are you experiencing this in?

## Steps to reproduce the issue

1. Step one.
2. Step two.
3. ???
4. Profit.

## Screenshots
<img width="572" alt="Screen Shot 2019-07-09 at 11 40 08 AM" src="https://user-images.githubusercontent.com/29963503/60914523-897f3c80-a23e-11e9-97a6-bfa6fee23d58.png">
<img width="617" alt="Screen Shot 2019-07-09 at 11 40 21 AM" src="https://user-images.githubusercontent.com/29963503/60914526-8c7a2d00-a23e-11e9-9ad2-3f60de2bf92a.png">

Please include screenshots to help illuminate the issue.

**Comment by edburyenegren-okta** [comment]
Styles are from:

```
.chzn-container-single.text-select .chzn-single {
  box-sizing: border-box;
  width: 16%;
  height: 30px;
  border-top-left-radius: 0;
  border-bottom-left-radius: 0;
  border-color: $very-light-gray $very-light-gray $dark-gray;
  cursor: pointer;
}
```

Weird to me that it intentionally has a darker bottom border, though not as high-contrast. Here's normal Courage:

<img width="558" alt="Screenshot 2019-07-11 18 13 46" src="https://user-images.githubusercontent.com/36284167/61095282-a74bcd80-a407-11e9-9a8f-b492d690f24c.png">

`$dark-gray` is `#b1b1b1` normally; remapped to `#777777` (pretty big jump)

**Comment by joejezowski-okta** [comment]
@edburyenegren-okta is this referring to the border underneath the caret (button portion) of the dropdown?

**Comment by edburyenegren-okta** [comment]
Correct, here are shots for comparison:

<img width="661" alt="Screenshot 2019-07-12 14 21 23" src="https://user-images.githubusercontent.com/36284167/61159290-678cf080-a4b0-11e9-91b7-63f1d87726c2.png">
<img width="667" alt="Screenshot 2019-07-12 14 21 10" src="https://user-images.githubusercontent.com/36284167/61159291-678cf080-a4b0-11e9-84c2-4f503f994ece.png">

**Comment by joejezowski-okta** [comment]
@edburyenegren-okta Ok just tested…Grey 300 is it's nearest neighbor. Let's go with that.

**Comment by edburyenegren-okta** [comment]
Current:

<img width="622" alt="Screenshot 2019-07-16 14 22 57" src="https://user-images.githubusercontent.com/36284167/61330786-417b8f00-a7d5-11e9-9342-9a2798e46796.png">

Remapped:

<img width="629" alt="Screenshot 2019-07-16 14 23 02" src="https://user-images.githubusercontent.com/36284167/61330785-417b8f00-a7d5-11e9-87e0-0fe9fb2541b7.png">

Looks much closer to me. @joejezowski-okta?

**Comment by joejezowski-okta** [comment]
Yup. Good!
