### ISSUE TITLE
Report badges are wrong color

### ISSUE THREAD

**Issue by joejezowski-okta** [okta/odyssey#130]
## Detailed description

Badges are dark red and should be the base red

> Is this issue related to a specific component?

> What did you expect to happen? What happened instead?

> What browser & version are you experiencing this in?

## Steps to reproduce the issue

1. Log in
2. Go to Admin
3. Reports

## Screenshots

Please include screenshots to help illuminate the issue.

<img width="126" alt="Screen Shot 2019-07-09 at 11 41 57 AM" src="https://user-images.githubusercontent.com/49886075/60914596-b16ea000-a23e-11e9-91fe-61ff17b44c7c.png">

**Comment by edburyenegren-okta** [comment]
Is this a Courage component?

**Comment by joejezowski-okta** [comment]
Not sure…

It should be `Red` though. It got mapped to `Dark Red`

**Comment by joejezowski-okta** [comment]
@edburyenegren-okta does this have a gradient overlay as well?

**Comment by edburyenegren-okta** [comment]
Non-Odyssey, closing.
