### ISSUE TITLE
"Groups" Secondary Nav is missing

### ISSUE THREAD

**Issue by joejezowski-okta** [okta/odyssey#133]
## Detailed description

The secondary navigation on the groups page is missing

> Is this issue related to a specific component?

Yes, secondary navigation

> What did you expect to happen? What happened instead?

Expected…should appear. It's gone.

> What browser & version are you experiencing this in?

Chrome Version 71.0.3578.98

## Steps to reproduce the issue

1. Admin
2. Directory
3. Groups

## Screenshots

Please include screenshots to help illuminate the issue.

<img width="226" alt="original" src="https://user-images.githubusercontent.com/49886075/60914755-04e0ee00-a23f-11e9-87a8-b95c5a326b9d.png">
<img width="384" alt="result" src="https://user-images.githubusercontent.com/49886075/60914758-05798480-a23f-11e9-8f86-cbef29e66905.png">

**Comment by edburyenegren-okta** [comment]
@joejezowski-okta where are you testing this? Is it possible that the DOM element is missing, not that the color is invisible now?

**Comment by joejezowski-okta** [comment]
@edburyenegren-okta 

When we were Q/A'ing I was here:
https://design-system-admin.trexcloud.com/admin/groups

I just went back when I saw your reply here and it's back to normal. Not sure what was going on. You can close this.
