### ISSUE TITLE
Text+Select button bottom border is too dark

### ISSUE THREAD

**Issue by rchild-okta** [okta/odyssey#134]
Example:
http://0.0.0.0:3000/form/edit-only-form

The "Text Select" example has a bottom border shadow that looks too dark.

**Comment by ganeshsomasundaram-okta** [comment]
![image](https://user-images.githubusercontent.com/40774045/60919254-20052b00-a24a-11e9-9b75-a4d46a4ea965.png)

**Comment by edburyenegren-okta** [comment]
Dupe of https://github.com/okta/odyssey/issues/129
