### ISSUE TITLE
Input group labels might be hard to read

### ISSUE THREAD

**Issue by rchild-okta** [okta/odyssey#135]
Example:
http://0.0.0.0:3000/form/edit-only-form

For input group labels, the grey-on-darker-grey might be hard to read - i.e. in the "input with label", "input with multiple labels", etc examples.

**Comment by edburyenegren-okta** [comment]
<img width="888" alt="Screenshot 2019-07-16 13 35 23" src="https://user-images.githubusercontent.com/36284167/61328601-35410300-a7d0-11e9-8358-8028bcf99730.png">

@joejezowski-okta another fix from the `$white-smoke-3` remap

**Comment by joejezowski-okta** [comment]
Looks good.
