### ISSUE TITLE
Dropdown placeholder text is lighter

### ISSUE THREAD

**Issue by ganeshsomasundaram-okta** [okta/odyssey#136]
![image](https://user-images.githubusercontent.com/40774045/60915278-4b831800-a240-11e9-9868-def568fd14e3.png)

## Detailed description

> Is this issue related to a specific component?

> What did you expect to happen? What happened instead?

> What browser & version are you experiencing this in?

## Steps to reproduce the issue

1. Step one.
2. Step two.
3. ???
4. Profit.

## Screenshots

Please include screenshots to help illuminate the issue.

**Comment by edburyenegren-okta** [comment]
The placeholder text here comes from normal `input` styling, so we probably don't want to darken it. I think the issue is that the selectize gradient is so much darker. 

The styles come from:

```
.selectize-control.single .selectize-input {
  -webkit-box-shadow: 0 1px 0 rgba(0,0,0,0.05), inset 0 1px 0 rgba(255,255,255,0.8);
  box-shadow: 0 1px 0 rgba(0,0,0,0.05), inset 0 1px 0 rgba(255,255,255,0.8);
  background-color: $white-smoke;
  background-image: -moz-linear-gradient(top, $white-2, $white-smoke-3);
  background-image: -webkit-gradient(linear, 0 0, 0 100%, from($white-2), to($white-smoke-3));
  background-image: -webkit-linear-gradient(top, $white-2, $white-smoke-3);
  background-image: -o-linear-gradient(top, $white-2, $white-smoke-3);
  background-image: linear-gradient(to bottom, $white-2, $white-smoke-3);
  background-repeat: repeat-x;
  filter: progid:DXImageTransform.Microsoft.gradient(startColorstr='#fffefefe', endColorstr='#fff2f2f2', GradientType=0);
}
```

`$white-2` is normally `#fefefe`; remapped to `#fafafa`
`$white-smoke-2` is normally `#f2f2f2`; remapped to `#d1d1d1`

**Comment by joejezowski-okta** [comment]
let's do `$white-smoke-2` to `$gray-0` and cancel out the gradient. 

we'll increase the contrast ratio that way which should increase readability.

**Comment by edburyenegren-okta** [comment]
<img width="941" alt="Screenshot 2019-07-16 13 31 43" src="https://user-images.githubusercontent.com/36284167/61327576-15a8db00-a7ce-11e9-944a-001407cbfacf.png">

@joejezowski-okta Gradient disappears with the `$white-smoke-3` to `cv('gray', '000')`. Looks okay to me, though!

**Comment by joejezowski-okta** [comment]
Yep…LGTM!
