### ISSUE TITLE
[App card] maybe smaller to read

### ISSUE THREAD

**Issue by santhoshbalakrishnan** [okta/odyssey#137]
Header text(See `SCIM Provisioning`) on app card became smaller and maybe too small to read.

<img width="422" alt="Screen Shot 2019-07-09 at 12 33 13 PM" src="https://user-images.githubusercontent.com/24683447/60917431-cd297480-a245-11e9-9de9-c4a55f79479c.png">

**Comment by edburyenegren-okta** [comment]
Noticed this as well - unrelated to our color work.
