### ISSUE TITLE
[Datalist] Header background/text contrast ratio

### ISSUE THREAD

**Issue by santhoshbalakrishnan** [okta/odyssey#138]
Datalist header background has become darker making it harder to read the text.

**Comment by edburyenegren-okta** [comment]
<img width="592" alt="Screenshot 2019-07-16 13 53 38" src="https://user-images.githubusercontent.com/36284167/61329002-2149d100-a7d1-11e9-8b2c-5d4d27b741f7.png">

@joejezowski-okta another one!

**Comment by joejezowski-okta** [comment]
Looks good!
