### ISSUE TITLE
[Form] Header and footer colors are off

### ISSUE THREAD

**Issue by santhoshbalakrishnan** [okta/odyssey#139]
<img width="643" alt="Screen Shot 2019-07-09 at 12 42 16 PM" src="https://user-images.githubusercontent.com/24683447/60917995-057d8280-a247-11e9-921e-b04381380f62.png">

**Comment by edburyenegren-okta** [comment]
<img width="939" alt="Screenshot 2019-07-16 13 47 42" src="https://user-images.githubusercontent.com/36284167/61328647-4d188700-a7d0-11e9-9e78-13488e79eadb.png">

@joejezowski-okta feeexed

**Comment by joejezowski-okta** [comment]
Looks good!
