### ISSUE TITLE
[EmptyState] Spacing is different

### ISSUE THREAD

**Issue by santhoshbalakrishnan** [okta/odyssey#140]
Difference seen here:

![spacing](https://user-images.githubusercontent.com/24683447/60918527-65285d80-a248-11e9-8a18-413ae07d13c9.gif)

This might not be an issue with the colors change, but making sure.

**Comment by edburyenegren-okta** [comment]
@santhoshbalakrishnan noticed this too! It's a delta between `master` and SkyLab in Courage - unrelated to Odyssey mappings.
