### ISSUE TITLE
[EmptyState] Links in empty state have the wrong colors

### ISSUE THREAD

**Issue by santhoshbalakrishnan** [okta/odyssey#141]
http://0.0.0.0:3000/multiView/empty-error-state-example

![link](https://user-images.githubusercontent.com/24683447/60918665-c0f2e680-a248-11e9-9a79-878d9a19b01a.gif)

**Comment by edburyenegren-okta** [comment]
As far as I can tell, this only uses browser default styling - no remappings or even Sass in play.
