### ISSUE TITLE
[icon] Android-16 is too light

### ISSUE THREAD

**Issue by santhoshbalakrishnan** [okta/odyssey#142]
<img width="165" alt="Screen Shot 2019-07-09 at 1 10 36 PM" src="https://user-images.githubusercontent.com/24683447/60919600-0adccc00-a24b-11e9-8723-156fed8fb2a1.png">

Before: 

<img width="151" alt="Screen Shot 2019-07-09 at 1 11 29 PM" src="https://user-images.githubusercontent.com/24683447/60919617-162ff780-a24b-11e9-9137-c36f28233358.png">

**Comment by edburyenegren-okta** [comment]
@joejezowski-okta this seems like one that should match the Android brand color, not our palette. Thoughts?

**Comment by santhoshbalakrishnan** [comment]
+1 to keeping it Android green.

**Comment by joejezowski-okta** [comment]
Agreed, keep it the Android green. Deprecate the color from DS use if possible.

**Comment by edburyenegren-okta** [comment]
<img width="143" alt="Screenshot 2019-07-16 14 41 31" src="https://user-images.githubusercontent.com/36284167/61331929-d2ec0080-a7d7-11e9-8065-ea9ac1a7bac5.png">

Actual Android green! I've marked and updated it in both the standard and remapped UI
