### ISSUE TITLE
Create list of components to ship EU on Odyssey

### ISSUE THREAD

**Issue by joejezowski-okta** [okta/odyssey#158]
Create a list of components that End User will require to launch on Odyssey. 

- [x] Joe look in Nicolas' current designs
- [x] Shred to compile list of HTML5 elements
- [x] Compare both lists

See: 
https://www.figma.com/file/9Zsa5MK4XYNeKbTlgxFhz3/UI-Inventory?node-id=0%3A1

### Foundations

**[L1] - Color [Blocked]**

**[L2] - Type**

**[L2] - Spacing**

**[L2] - Icons [Blocked]**

**[L3] - Buttons**

**[L3] - Inputs**

**[L4] - Tooltip**

**[L4] - Modal**

**[L4] - Navigation**

## HTML5 Baseline
This refers to standard styling for *unclassed* elements.

Ref doc: https://developer.mozilla.org/en-US/docs/Web/HTML/Element

When I mention "resets" below, I mean "establish baseline styling" not "unset values / set values to 0".

### MVP
*Elements we will need in order to ship.*

- `html` - a few resets we'll want to do
- `body` - a few resets we'll want to do
- headings (`h1`, `h2`, `h3`, `h4`, `h5`, `h6`) - establish defaults
- lists (`ul`, `ol`, `li`)
- anchors (`a`)
- emphasis (`em`) [formerly `i`]
- `img`
- `button`
- `dialog` (modal)
- `strong`

### Icing
*Elements we will definitely utilize, but may not need to ship with.*

- `table` and all contained elements
- `form`, `datalist`, `fieldset`, `input`, `label`, `legend`, `select`, `textarea`
- `blockquote`
- description lists (`dl`,`dd`,`dt`)
- `figure`,`figcaption`
- `pre`, `code`
- `abbr`
- `cite`
- `dfn`
- `kbd`
- `q`
- `samp`
- `time`
- `var`
- `video`
- `del`
- `ins`
- `meter`
- `progress`
- `details`, `summary`
- `menu`, `menuitem`

**Comment by edburyenegren-okta** [comment]
@joejezowski-okta i added a subset of HTML5 elements in two groups: MVP and Icing. There are more items we may want to tackle later, but I didn't even want them surfaced here.

**Comment by edburyenegren-okta** [comment]
> [L0] - Grid

IMO we shouldn't have a standard grid. After going over the possibilities of css grid and flexbox with EU, they were happy to roll their own grid solution based on their content needs.

> Type: Links

I think we should treat these as separate from type since they have a ton of specific concerns.

> Type: Error

Curious where this is from. IMO anything that has an error state should be represented by the component, not general text. (e.g. Form errors should be covered by Form, not Type)

> Buttons

Is this based off of EU inventory or what you think DS should supply? I'd rather look at their current UI as a problem statement that we come back with an answer for.

> Modal

Could we take the Desktop/Mobile distinction off? IMO *everything* we make should be RWD ready before it ships.

> Navigation

Accordion is probably a separate component. Where they're using it in the drawer, it's not really a nav element.

**Comment by joejezowski-okta** [comment]
> IMO we shouldn't have a standard grid. After going over the possibilities of css grid and flexbox with EU, they were happy to roll their own grid solution based on their content needs.

How do we manage having common margin and gutters globally?

**Comment by joejezowski-okta** [comment]
> I think we should treat these as separate from type since they have a ton of specific concerns.

I see your point from a development standpoint, however it's really helpful to package text together in Figma for designers that way.

**Comment by joejezowski-okta** [comment]
> Is this based off of EU inventory or what you think DS should supply? I'd rather look at their current UI as a problem statement that we come back with an answer for.

EU inventory. Based on what I see, I think it's a good baseline.

**Comment by joejezowski-okta** [comment]
> Could we take the Desktop/Mobile distinction off? IMO _everything_ we make should be RWD ready before it ships.

What is RWD? 

I do see value in having everything responsive. However, this is just speaking from my own experience and tons of testing…but having a mobile/small screen specific modal produces a far better user experience and allows for better use of screen real estate. As a caveat to my statement I think it should be an option as to how we let designers and developers choose the style of modal they want.

Happy to explain further in a meeting :)

**Comment by edburyenegren-okta** [comment]
> > IMO we shouldn't have a standard grid. After going over the possibilities of css grid and flexbox with EU, they were happy to roll their own grid solution based on their content needs.
> 
> How do we manage having common margin and gutters globally?

Fair. We should probably document some general Layout guidelines. I think @nickarcidy-okta might have done some work here already around when to use which spacing sizes for margins and padding.

**Comment by edburyenegren-okta** [comment]
> > I think we should treat these as separate from type since they have a ton of specific concerns.
> 
> I see your point from a development standpoint, however it's really helpful to package text together in Figma for designers that way.

Hm. I don't think the system (to a consumer) should make "Generic Error Text" available to anyone.

Even in the Figma context, it relies on a Designer saying, "I want to make some text red to show an error in a use case that the system doesn't cover."

If they aren't using a form or callout or any of our other "Error" variant components, that raises a red flag for me. Where is this error coming from? Why aren't they using existing UI? etc

In the case that it's a valid use not covered by the system, they should create an interim component for it and open an issue with us. We don't want folks going, "oh, i can just use red error text whenever" simply because it exists.

**Comment by edburyenegren-okta** [comment]
> > Is this based off of EU inventory or what you think DS should supply? I'd rather look at their current UI as a problem statement that we come back with an answer for.
> 
> EU inventory. Based on what I see, I think it's a good baseline.

Would you be comfortable just saying "Buttons" and then identifying the variants when we are working on them? I am viewing this list, once public, as a promise. I'd rather limit that promise to "Components we will produce" not "Every variant we will produce".

**Comment by edburyenegren-okta** [comment]
> > Could we take the Desktop/Mobile distinction off? IMO _everything_ we make should be RWD ready before it ships.
> 
> What is RWD?
> 
> I do see value in having everything responsive. However, this is just speaking from my own experience and tons of testing…but having a mobile/small screen specific modal produces a far better user experience and allows for better use of screen real estate. As a caveat to my statement I think it should be an option as to how we let designers and developers choose the style of modal they want.
> 
> Happy to explain further in a meeting :)

RWD = Responsive Web Design

IMO all of that should happen automatically unless it's a content-specific breakpoint.

e.g. If all modals are system standard in size, placement, and behavior, they should respond to screen size in the same way.

In either case, happy to table for now, but could we remove the variants from the list (as with Button)?

**Comment by edburyenegren-okta** [comment]
I hate that threaded comments aren't supported for non-code commenting. Wtf Github.

**Comment by joejezowski-okta** [comment]
> In either case, happy to table for now, but could we remove the variants from the list (as with Button)?

Hmm…I think we should chat in person so we're not lost in translation over text. Nicolas has use cases for both of these scenarios already designed.

**Comment by joejezowski-okta** [comment]
> > > Is this based off of EU inventory or what you think DS should supply? I'd rather look at their current UI as a problem statement that we come back with an answer for.
> > 
> > 
> > EU inventory. Based on what I see, I think it's a good baseline.
> 
> Would you be comfortable just saying "Buttons" and then identifying the variants when we are working on them? I am viewing this list, once public, as a promise. I'd rather limit that promise to "Components we will produce" not "Every variant we will produce".

100% makes sense.

**Comment by edburyenegren-okta** [comment]
> > In either case, happy to table for now, but could we remove the variants from the list (as with Button)?
> 
> Hmm…I think we should chat in person so we're not lost in translation over text. Nicolas has use cases for both of these scenarios already designed.

In EU the error text is still component-based - either as a part of "App Card" or as a "Pill", right?

In either case, Nicolas isn't adding free-standing red text to a content area; the red color reflects a variant of a component (or component part).

**Comment by joejezowski-okta** [comment]
> > > I think we should treat these as separate from type since they have a ton of specific concerns.
> > 
> > 
> > I see your point from a development standpoint, however it's really helpful to package text together in Figma for designers that way.
> 
> Hm. I don't think the system (to a consumer) should make "Generic Error Text" available to anyone.
> 
> Even in the Figma context, it relies on a Designer saying, "I want to make some text red to show an error in a use case that the system doesn't cover."
> 
> If they aren't using a form or callout or any of our other "Error" variant components, that raises a red flag for me. Where is this error coming from? Why aren't they using existing UI? etc
> 
> In the case that it's a valid use not covered by the system, they should create an interim component for it and open an issue with us. We don't want folks going, "oh, i can just use red error text whenever" simply because it exists.

I think your first statement is exactly the scenario we should support. I don't want anyone to assume that Odyssey has _every_ UI element already built for them, or in this case an error state that is perfect for every scenario.

My two cents…If we document color properly and define usage rules, they should use it. Also, in the example of the form…without red text in itself we cant make error states happen.

**Comment by joejezowski-okta** [comment]
> * `html` - a few resets we'll want to do
> * `body` - a few resets we'll want to do

For my own sake, what do you mean here? Can you specify?

**Comment by edburyenegren-okta** [comment]
@joejezowski-okta stuff like `* { box-sizing: border-box; }` or `font-size: 100%` - super general baselines.
