### ISSUE TITLE
Create a standard template for documentation

### ISSUE THREAD

**Issue by edburyenegren-okta** [okta/odyssey#159]
We should have a content template (or set of them) for how we document components, foundational styles, and layouts.

ex:

Title
Lede
Usage
Variants
Content Guidelines

with examples of what is expected for formatting and content at all levels

**Comment by joejezowski-okta** [comment]
@edburyenegren-okta can you write a description for this?

**Comment by edburyenegren-okta** [comment]
@arnoldsandoval-okta do we have any dupe tickets for this?

**Comment by edburyenegren-okta** [comment]
Done.
