### ISSUE TITLE
Support prefers-reduced-motion (feature request)

### ISSUE THREAD

**Issue by alexdahl-okta** [okta/odyssey#16]
Some components, such as modals, include animated transitions.

To drive them, the design system includes abstracts such as `$base-duration` and `$base-timing`.  Currently, these abstracts are constant and apply on all devices.

Animations are an accessibility concern, as they can cause difficulty for a wide range of people. 
- https://alistapart.com/article/accessibility-for-vestibular/
- https://developers.google.com/web/updates/2019/03/prefers-reduced-motion
- https://css-tricks.com/revisiting-prefers-reduced-motion-the-reduced-motion-media-query/ 

The [`prefers-reduced-motion`](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-reduced-motion) media query can detect if the user has requested animations to be reduced.

Similarly, the [`update`](https://www.w3.org/TR/mediaqueries-4/#update) media feature can detect if the device has limited support for animations (print, e-ink, low-power).

The system should treat animation as a progressive enhancement, and only enable it if appropriate.

- [Carbon recommends](https://www.carbondesignsystem.com/guidelines/motion/resources#adaptive-interface-motion-design) considering both the person and the device, and to "Always provide alternatives for interface state transitions."
- [Aurora uses](https://github.com/gctools-outilsgc/aurora-design-system/search?q=motion&unscoped_q=motion) `prefers-reduced-motion` to disable transitions on many components.

**Comment by edburyenegren-okta** [comment]
@arnoldsandoval-okta seems like something we could create a mixin for
