### ISSUE TITLE
Tags

### ISSUE THREAD

**Issue by edburyenegren-okta** [okta/odyssey#163]
- [x] Audit current components
- [x] Audit product needs
- [x] Build Figma Component
- [x] Design Docs
- [x] Refactor existing CSS
- [x] Eng Doc update

**Comment by nickarcidy-okta** [comment]
V1 pre-Odyssey documentation:

https://oktawiki.atlassian.net/wiki/spaces/UX/pages/670761058/Lozenge+Tag+Component+V1+Provisional

**Comment by nickarcidy-okta** [comment]
Under chips, performing for this sprint:

- Define all chip variants
- Product and web audit for chip use
- Visual design explore and finalization
- Guidelines for use

**Comment by nickarcidy-okta** [comment]
At the end of the last sprint, I brought Chips about 95% of the way to completion (R&D, research, reviewing with team, visual design exploration, documentation). All that needs to be done is a final review with the team on both visual design and documentation, as well as building out final Figma components.

https://www.figma.com/file/UJUJQSbOynFEU8ow7FMZs4/Chips?node-id=0%3A1

**Comment by nickarcidy-okta** [comment]
Tags and tag guidelines have been reviewed by the team and have had Figma components built out. Seeking a final review so we can add these to the UI Kit! Breaking out Status as its own new component. 

https://www.figma.com/file/UJUJQSbOynFEU8ow7FMZs4/Chips?node-id=0%3A1

**Comment by nickarcidy-okta** [comment]
Seeking final review on tags! Paging @edburyenegren-okta @joejezowski-okta @johnintrater-okta !

Documentation and final component provided in this Figma:

https://www.figma.com/file/UJUJQSbOynFEU8ow7FMZs4/Chips?node-id=0%3A1

Status has been broken out as a separate component and all progress up until this point has been captured here: #273

**Comment by johnintrater-okta** [comment]
LGTM @nickarcidy-okta. Can you update the Figma file to be named Tags just to ensure clarity?

**Comment by nickarcidy-okta** [comment]
On it!

**Comment by edburyenegren-okta** [comment]
@FeliciaWang-okta from your mocks, this looks like the appropriate use case for sure.

Our main concern so far has been distinguishing "Tag" from "Status" (as they tend to have very similar visual treatments), but your ASA work falls right in line with what we expect.

**Comment by FeliciaWang-okta** [comment]
@edburyenegren-okta yeah I agree that our ASA labels have virtually the same use case as "tags" in other products. However, we're expecting labels to have some additional functionality that align with existing common behavior in other infrastructure tools, like Kubernetes: https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/

Specifically, we are formatting labels in the `key : value` format with the expectation that we will one day introduce label selectors. Today, there are still no concrete plans to implement label selectors, so our labels will simply follow the `key : value` format but behave as normal tags, but wanted to call out the intent and plans behind this decision and this potential distinction from traditional tags.

**Comment by alexdahl-okta** [comment]
+1 from dev docs and OIN Manager.
