### ISSUE TITLE
Basic Inputs (EU needs)

### ISSUE THREAD

**Issue by edburyenegren-okta** [okta/odyssey#165]
- [x] Audit existing elements in Odyssey
- [x] Audit needs of product
- [x] Rebuild Components in Figma
- [x] Write docs in Figma
- [x] Rebuild Components in Code
- [x] Update docs site

**Comment by edburyenegren-okta** [comment]
@santhoshbalakrishnan could you let us know which form elements EU needs?

**Comment by santhoshbalakrishnan** [comment]
- [ ] Text input
- [ ] Password input
- [ ] Checkbox
- [ ] Readonly versions of all the above

PS. This does not include the settings page.

**Comment by edburyenegren-okta** [comment]
I would pitch that we add Radios here as well since we're tackling Checkboxes - thoughts, @joejezowski-okta?

**Comment by joejezowski-okta** [comment]
Yep, agreed
