### ISSUE TITLE
Adjust Type Scale

### ISSUE THREAD

**Issue by edburyenegren-okta** [okta/odyssey#168]
To compress and streamline type use, let's try: 1.2308 

https://www.modularscale.com/?16&px&1.2308

This gives us 13px as a single available "small" size for legalese and makes headlines easier to apply.

- [x] Code updated
- [x] Docs updated
- [x] Figma updated

**Comment by joejezowski-okta** [comment]
@edburyenegren-okta how is line height calculated in the modular scale? Is it just set to 100% based on how it's programmed?

**Comment by edburyenegren-okta** [comment]
@joejezowski-okta currently, they're set separately. We have variables for body and heading line-heights (1.5 and 1.2 respectively, I think).

I tried to get something like https://www.gridlover.net/try working, but with the dynamically generated line-heights (for a perfect vertical rhythm), you end up with some sizes where the line-height is less than allowed for a11y. 

example worst-case scenario: if your base line-height ends up being `24px` and one of the type sizes available is `24px`, the line-height will be set to `1` for that size.

**Comment by edburyenegren-okta** [comment]
@joejezowski-okta code is merged + docs updated for new scale. Any work to be done in Figma yet?
