### ISSUE TITLE
Type Standards

### ISSUE THREAD

**Issue by edburyenegren-okta** [okta/odyssey#169]
Establish baseline type styles for Odyssey.

- [x] Headings: h1-h6, unclassed
- [x] Font weights: when / when not to use them - 000 through 900 (?)
- [x] Color for Type + Type on Color

@edburyenegren-okta 

- [x] Docs Site:
- [x] Update color to Grey 900
- [x] Update Specimen
- [x] Remove Thin weight
- [x] Remove usage section

----

- [x] Code
- [x] Figma
- [x] Docs

**Comment by joejezowski-okta** [comment]
@edburyenegren-okta all type is `Grey-900`
