### ISSUE TITLE
Initial CSS "Reset"

### ISSUE THREAD

**Issue by edburyenegren-okta** [okta/odyssey#171]
For MVP we'll need:

- [x] `html` - font-size, box-sizing
- [x] `body` - same as above
- [x] `img` - basic styles for fluid images

**Comment by edburyenegren-okta** [comment]
@joejezowski-okta let's review a more robust list with @johnintrater-okta and @nickarcidy-okta tomorrow - just to make sure we're not going to miss any basics.

**Comment by joejezowski-okta** [comment]
100%
