### ISSUE TITLE
Ordered / Unordered Lists

### ISSUE THREAD

**Issue by edburyenegren-okta** [okta/odyssey#172]
Basic, unclassed styling for lists.

----

- [ ] Docs
- [ ] Code

**Comment by joejezowski-okta** [comment]
@edburyenegren-okta Are we only thinking about these lists as they pertain to text? For instance the "Apps" on the EU experience are technically <li>'s.

**Comment by edburyenegren-okta** [comment]
Ah! This is only for *unclassed* `<li>`s like:

<ul>
<li>Dog</li>
<li>Cat</li>
</ul>

We won't require that all of the default HTML styling for unclassed elements carry over to anything more specific.
