### ISSUE TITLE
Figma color Palette

### ISSUE THREAD

**Issue by joejezowski-okta** [okta/odyssey#175]
- [x] Refine color Figma color palette to reflect usage rules.
- [x] Update nomenclature to standard color names

**Comment by edburyenegren-okta** [comment]
Re: naming, our last convo with @nickarcidy-okta about color has pushed me back into the realm of Success, Action, Danger, etc - at least at the mapping/implementation level. Using hue names for colors there is going to make things much more brittle (especially when we get into providing themes or dark mode down the road).
