### ISSUE TITLE
Glossary Page for Docs and Figma

### ISSUE THREAD

**Issue by edburyenegren-okta** [okta/odyssey#181]
We should create a single page doc for any design system (or adjacent terms).

Currently confused about terminology? Had to look something up before? Comment below!

**Comment by alexdahl-okta** [comment]
For clarity: I read this issue as sort of meta documentation? It's sort of about universal facts? "An `anchor` is...", "`Line height` or `leading` is...", etc?

Versus #87, which hypothetically contains decisions the system has made – voice and tone for Odyssey. "Use `add` for...", "use `save` for...", etc?

**Comment by edburyenegren-okta** [comment]
@alexdahl-okta accurate. This is an actual glossary, not language guidelines.

**Comment by alexdahl-okta** [comment]
Thanks! I might have one, though it might be a little different. 

Whichever term refers to consumers of the system – a project that is adopting and using Odyssey. `consumer`, `adopter`, `product`, `app`, `project`, etc?

(2¢: `product` and `app` may not resonate with all kinds of projects. `consumer` may be ambiguous and unfamiliar. `adopter` is kind of nice?)

**Comment by edburyenegren-okta** [comment]
Moving this from untriaged to Icebox - good idea, but we aren't sure when or how to best implement this yet (or if Odyssey is the best place for broad education). As we revamp our docs site, there will be more opportunities to address this.

I'll cycle this question to the channel to see if there's a more urgent or robust need.
