### ISSUE TITLE
Documentation Site

### ISSUE THREAD

**Issue by joejezowski-okta** [okta/odyssey#183]
Update <title> to `Odyssey`

Update front page copy to say:

> Odyssey - the Okta Design System
> Hello and welcome! These are the early days of Okta's design system. Feel free to poke around, test things out, and explore our guidelines.
> 
> Please note, we've recently changed the name of our Design System from "NIM" to Odyssey. Our packages still reflect our old name. Please stay tuned for further updates.

**Comment by edburyenegren-okta** [comment]
Closing because change is complete
