### ISSUE TITLE
Pagination

### ISSUE THREAD

**Issue by johnintrater-okta** [okta/odyssey#184]
This is something that came up in an ASA meeting but we should be able to give as much guidance as possible on what to do or not to do help guide the design team re pagination. 

## Detailed description

> Is this issue related to a specific component?

> What did you expect to happen? What happened instead?

> What browser & version are you experiencing this in?

## Steps to reproduce the issue

1. Step one.
2. Step two.
3. ???
4. Profit.

## Screenshots

Please include screenshots to help illuminate the issue.

**Comment by edburyenegren-okta** [comment]
Is this blocked by Button Groups? are they related?

**Comment by jeffbelser-okta** [comment]
@johnintrater-okta @edburyenegren-okta :100: this is a good one for admin as well.

Honestly there is alot to consider here if we're going to do this correctly so I recommend removing the `good-first-issue` label. RTL support, a11y planning and a nice compact look and feel would be among those items I'm thinking about for this.

**Comment by alexdahl-okta** [comment]
FWIW, I'm enjoying GitHub's current pagination style:

<img width="1260" alt="github" src="https://user-images.githubusercontent.com/26014482/93252259-f0e12800-f730-11ea-989c-16eb724c6db5.png">
