### ISSUE TITLE
Figma Artboard Setup/Guidance

### ISSUE THREAD

**Issue by edburyenegren-okta** [okta/odyssey#188]
- [x] Create a standard art-board size for designers to begin projects
- [ ] Created best practices on how to use
- [ ] Refactor Modals to fit

**Comment by edburyenegren-okta** [comment]
@joejezowski-okta this still something that we want to do / needs to get done?

**Comment by johnintrater-okta** [comment]
@edburyenegren-okta @joejezowski-okta  curious - why is this issue a priority atm?
