### ISSUE TITLE
Search & filter pattern/components

### ISSUE THREAD

**Issue by FeliciaWang-okta** [okta/odyssey#189]
Search & filter instances of an object (e.g. search/filter for a specific user in a list of users, search/filter for a specific resource in a list of resources, etc.)

**Comment by LanaChoi-okta** [comment]
yes! this is really important. for custom admin roles, we have a table that needs to be filtered and searchable. upvoting this!

**Comment by joejezowski-okta** [comment]
@LanaChoi-okta have you done any other exploration than what was posted in Slack recently? Feel free to post in this thread for added context!
