### ISSUE TITLE
External link icon should scale with font size

### ISSUE THREAD

**Issue by joejezowski-okta** [okta/odyssey#19]
(Fully deserves investigation and consideration, not sure if this is truly a Nim bug or what the best fix is.)

For text at font-sizes other than 16px, the external link icon has trouble.
If <16px, the right and bottom edges of the icon start to be clipped.
If >16px, the icon starts to repeat.

The ::after box is scaling with the font size (it has a width and height of 1em), but its SVG background image is not.

![bug](https://user-images.githubusercontent.com/49886075/60304030-fd3f5200-98ec-11e9-91ca-975250195037.png)

 

I assume scaling with the font size is desirable.

At a glance, background-size: 1em; seems like a possible solution.

![bgsize](https://user-images.githubusercontent.com/49886075/60304019-f284bd00-98ec-11e9-9a25-1a33d5d6d45f.png)

Nim 0.1.0-beta.2407.g46f83be
Chrome 73.0.3683.103
macOS 10.13.6

**Comment by arnoldsandoval-okta** [comment]
I tested this locally and it seems to work fine. @joejezowski-okta do you know who I can talk to, to see if the issue still persists?

When stress testing locally there is no issue (other than a visual one, where the external icon is blue, but the visited link is purple)

![image](https://user-images.githubusercontent.com/62259644/80446878-d109ae80-88cc-11ea-8bca-bffc2bb3bd13.png)

Moving to review in the interim.

**Comment by alexdahl-okta** [comment]
👋 @arnoldsandoval-okta, I think I originally filed this one. Trying out things in Inspector on developer.okta.com docs now, I can't replicate.

So, not sure how or when it was resolved, but does seem safe to close. 🎉 (Dev docs has other issues related to the icon appearing, but I'm pretty sure they're not Odyssey issues.)

@edburyenegren-okta, I recall something else about the external link icon came up recently? Any other input here, or safe to close?

**Comment by edburyenegren-okta** [comment]
@alexdahl-okta I think this is safe to close - End User was having the same issue, but they couldn't replicate after updating to current Odyssey

**Comment by arnoldsandoval-okta** [comment]
Great! Closing.
