### ISSUE TITLE
External Anchors

### ISSUE THREAD

**Issue by mattkaniaris-okta** [okta/odyssey#195]
### Summary

Anchors use `a[target=_blank]:not([href^="mailto:"])::after` to target "external links", but not all `target=_blank` links are external.

### MVP functionality

Use a class.

### Timeline / Project

No.

**Comment by edburyenegren-okta** [comment]
@mattkaniaris-okta is this a language issue or an implementation issue?

By external, I think @stevennguyen-okta meant "opens in new tab" not "takes you to another property".

Are there cases for `_blank` that won't open in a new tab/window?

**Comment by stevennguyen-okta** [comment]
When I originally worked on the guidelines for links, "external" meant that a new tab would open. An external link that takes you to another property is often correlated, but not always true. 

Here's the guidelines:
Use an external link when:

> Use an external link when:

> The destination of the link aids in the completion of a task on the current tab (e.g. additional information such as help documentation)
> Opening the link in the current tab would result in a significant loss of data or interruption of flow (e.g. while filling out a long form)

For example, the user may be need to reference another part of the Admin app for the user to set something else up (same property). Or you may want to link to a 3rd party API documentation (different property) to understand how to fill out some form. In both cases, opening in a new tab would be recommended.
