### ISSUE TITLE
Select and Selectize

### ISSUE THREAD

**Issue by mattkaniaris-okta** [okta/odyssey#196]
## Detailed description

We should not be using any third party JS in the design system - `selectize` also requires jQuery. `Selectize.js` turns `<Select />`s into `<input type="text"/>` and does other crazy stuff.  Without `Selectize`, no styles are applied.  The design system`select` is unusable in this form.

**Comment by edburyenegren-okta** [comment]
@mattkaniaris-okta we don't intend to make use of / rely on Selectize in the future; it's only used in the design docs today as a way to proof the styles we'd been testing.

we plan on offering a no-js solution for plain `select`s soon.

**Comment by mattkaniaris-okta** [comment]
@edburyenegren-okta 

That makes sense.  Unfortunately, the styles heavily conflict with our own while at the same time we can't use the Odyssey implementation.

**Comment by edburyenegren-okta** [comment]
@mattkaniaris-okta we are removing Selectize as a dep in the next release, adding in support for Choices, and ensuring we have styles for vanilla selects as well.
