### ISSUE TITLE
Autocomplete 

### ISSUE THREAD

**Issue by magizh-okta** [okta/odyssey#198]
### Summary

Autocomplete can be client side or server side. Currently it is used as a part of pickers and dropdowns. 

There seems to be some inconsistencies in old DS where we have at least two different pickers. One where empty search result is displayed as "No results found" vs no text/ui to define empty state. 

Would be helpful to define that. 

This is slightly related to usage of selectize vs select issue. selectize doesnt have an empty state in autocomplete. 
https://github.com/okta/odyssey/issues/196

### MVP functionality
* define functionality and states before skinning would help. 
* make sure each state has Accessibility.

### Timeline / Project

Preferably By end of Oct. 
Would be helpful to resolve issues in current UIs as well.

**Comment by edburyenegren-okta** [comment]
@magizh-okta for clarity, is this a request to ensure that auto-complete behavior works in the JS-enabled Select solution we use? (in the current case, Choices.js)?
