### ISSUE TITLE
New DS Modal is missing subtitle attribute

### ISSUE THREAD

**Issue by joejezowski-okta** [okta/odyssey#24]
New DS based modal is missing the "subtitle" which is used in our current courage component. 
e.g., Upload RUM Help Text modal in SU -> Apps page

![Screen Shot 2019-06-27 at 3 09 32 PM](https://user-images.githubusercontent.com/49886075/60304219-940c0e80-98ed-11e9-8336-8f6fa82b748c.png)

Sample Code-

export default ModalDialog.extend(
  {
    title: 'Upload RUM Help Text',
    subtitle: 'File type must be .zip',

    className: 'rum-helptext-upload-form',

    params: {
    ...

Ref: https://github.com/okta/okta-ui/pull/829/files#r255665176

**Comment by joejezowski-okta** [comment]
@edburyenegren-okta Can we close this?

**Comment by edburyenegren-okta** [comment]
Yup - we've agreed that Courage functionality does not dictate future behavior.
