### ISSUE TITLE
Small btns in form-actions are not small...

### ISSUE THREAD

**Issue by mattkaniaris-okta** [okta/odyssey#251]
<img width="556" alt="Screen Shot 2019-10-11 at 2 42 38 PM" src="https://user-images.githubusercontent.com/41267187/66686781-64330d80-ec35-11e9-9a79-a9fc66fd6a56.png">

```HTML
<section class="form--actions">
  <button class="button is-button-secondary is-button-small" type="button">sm btn</button>
  <button class="button is-button-primary" type="submit" name="Button">big btn</button></section>
```

This is because of the `display: flex` in `form--actions`.

**Comment by ramkrishn123** [comment]
Add scss in button.scss file in .is-button-small class to get smaller fonts.
