### ISSUE TITLE
Clear btns can not be dangerous.

### ISSUE THREAD

**Issue by mattkaniaris-okta** [okta/odyssey#252]
```HTML
<button class="button is-button-clear is-button-danger" type="button">Clear</button>
```
A focused `is-clear`, `is-dangerous` has some dangerous and some primary colors.

<img width="113" alt="Screen Shot 2019-10-11 at 2 53 05 PM" src="https://user-images.githubusercontent.com/41267187/66687234-d8ba7c00-ec36-11e9-80a3-874614d0a6c8.png">

**Comment by edburyenegren-okta** [comment]
Clear buttons are not intended to be used like this, per the docs.
