### ISSUE TITLE
Buttons should play more nicely with Anchors...

### ISSUE THREAD

**Issue by mattkaniaris-okta** [okta/odyssey#256]
### Summary

including `<a><button class="button"></a>` and `<a class="button"></a>`.

The docs say:

> Don't use buttons to navigate users around the site or product; use links instead.

... which is reasonable for links in `<p>`s, but styling the primary call to action as a button is a very common idiom.  I propose that Odyssey support these features but discourage their use.

**Comment by edburyenegren-okta** [comment]
`<a><button></button></a>` is specifically disallowed by the spec. 

there may be a need for more grandiose link UI for marketing purposes, but I don't think conflating two distinct UI concepts in product is good practice

**Comment by edburyenegren-okta** [comment]
After a bit of discussion, Odyssey won't be officially supporting this in the near future.
