### ISSUE TITLE
Make priority labels: High/Med/Low

### ISSUE THREAD

**Issue by edburyenegren-okta** [okta/odyssey#267]

**Comment by joejezowski-okta** [comment]
@edburyenegren-okta Can you check this?

**Comment by edburyenegren-okta** [comment]
@joejezowski-okta how would you feel about `priority: high`, etc instead?

it's not as nice looking, but it'll help em stay grouped together when viewing the list

**Comment by joejezowski-okta** [comment]
@edburyenegren-okta makes sense. fixed
