### ISSUE TITLE
Toast Notification - Build

### ISSUE THREAD

**Issue by FeliciaWang-okta** [okta/odyssey#269]
### Summary

Today, there is not a dedicated component for system-wide notifications. The callout component is similar but not an appropriate substitute as it should be used inline with the rest of the layout, is not dismissible (in Odyssey) and should be used for showing information about the system rather than a direct response to user actions. 

### MVP functionality

Toast with message only, auto-dismissed after X seconds without user action. 
Toast with message and one button, requires user action to dismiss. 
Toast with message and two buttons, requires user action to dismiss. 

Guidelines on were notifications should live after toast is dismissed in context. (For example, should they live in an aggregated notifications component on the dashboard?)

### Timeline / Project

ASA has a need to redesign our system status messaging. Timeline has not been prioritized yet but this is a high priority intent.

**Comment by joejezowski-okta** [comment]
![image](https://user-images.githubusercontent.com/49886075/88220487-e5cdb800-cc17-11ea-9471-0a1e7fd42358.png)
