### ISSUE TITLE
Indeterminate Checkbox

### ISSUE THREAD

**Issue by joejezowski-okta** [okta/odyssey#270]
### Summary

Need to create a checkbox for Indeterminate values

### MVP functionality

Just add another state to existing component

### Timeline / Project

Is this request related to an upcoming release or project?

- [x] Code
- [x] Dev Docs
- [x] Design
- [x] Design Docs

https://www.figma.com/file/JW50oK4VDmN6M8cQcx5dPh6g/Odyssey-UI-Kit?node-id=3617%3A19

**Comment by joejezowski-okta** [comment]
@edburyenegren-okta 
I know you'll probably tack this with CSS, but here's my design for reference:
https://www.figma.com/file/JW50oK4VDmN6M8cQcx5dPh6g/Odyssey-UI-Kit?node-id=3533%3A8

If this is any help, I also referred to this page:
https://css-tricks.com/indeterminate-checkboxes/

**Comment by edburyenegren-okta** [comment]
@joejezowski-okta anything needed in Figma here? we're good on web docs and code.
