### ISSUE TITLE
Include Font Files

### ISSUE THREAD

**Issue by bretterer** [okta/odyssey#272]
### Summary

Fonts are part of the odyssey package however they are not included in this repo.

### MVP functionality

Include fonts as part of the package

### Timeline / Project

Is this request related to an upcoming release or project? Yes, Its part of the D.O.C. Prose layout.

<img width="1480" alt="Screen Shot 2019-11-18 at 3 12 26 PM" src="https://user-images.githubusercontent.com/1906920/69089153-d7d6f000-0a15-11ea-94ef-2260ac0bef75.png">

**Comment by edburyenegren-okta** [comment]
Closing - we won't be able to include any of our licensed fonts as part of the OSS package.

Okta UI is going to be serving an internally-hosted package for Okta fonts. ODS will keep the font stack the same, but will continue styling with system fonts as an expectation outside of products that utilize Bacon.
