### ISSUE TITLE
Status

### ISSUE THREAD

**Issue by nickarcidy-okta** [okta/odyssey#273]
### Summary

The status component has been broken off from the overall chip form-factor into its own component. The status component should be used to clearly indicate the current state of an item using semantic coloring.

### MVP functionality

A simple and consistent way to present semantic states.

### Timeline / Project

This item has has progressed to a near complete state, but needs to be taken across the finish line. Progress on the Chips parent component can be found here, with research, visual design exploration, and guidelines for the Status sub-component.

https://www.figma.com/file/UJUJQSbOynFEU8ow7FMZs4/Chips?node-id=0%3A1

I've started a new Figma file with open edit access dedicated to Status here:

https://www.figma.com/file/h4qlnMbCZmD1ZmW8pY5EKR/Status?node-id=0%3A1

**Comment by FeliciaWang-okta** [comment]
+1 from ASA on prioritizing this

**Comment by alexdahl-okta** [comment]
+1 from dev docs and OIN Manager. We have a variety of status and other kinds of tags, and would love guidance on when a status is appropriate or not.

An example from OIN Manager:

<img width="405" alt="Screen Shot 2020-03-06 at 4 41 45 PM" src="https://user-images.githubusercontent.com/26014482/76135271-75582e80-5fc9-11ea-8c92-370a860ecb2c.png">

<img width="405" alt="Screen Shot 2020-03-06 at 4 41 55 PM" src="https://user-images.githubusercontent.com/26014482/76135276-79844c00-5fc9-11ea-8384-ee3c557f14db.png">

**Comment by edburyenegren-okta** [comment]
Closed by #489
