### ISSUE TITLE
Font-size increase causes header navigation dropdowns to linebreak

### ISSUE THREAD

**Issue by edburyenegren-okta** [okta/odyssey#304]
The dropdown menu in the main navigation has a fixed size. With the global font size increasing, the links began to wrap and make connected words, disjointed. 

The fix is to either increase the width of the dropdown, or make it conditionally wider to accommodate the text.

Issue 1: https://oktawiki.atlassian.net/wiki/spaces/UX/pages/751567447/Courage+Re-style+Admin+Adoption+Issues+for+Shared+Code

**Comment by edburyenegren-okta** [comment]
I've changed this from `width: 200px` to `min-width: 200px` - it's not the best way to build these, but it'll preserve the original design and remove the buggy behavior.

**Comment by joejezowski-okta** [comment]
Any chance to pop a screen grab in here from the offending link? (Security>Delegated Authentication)

**Comment by edburyenegren-okta** [comment]
https://github.com/okta/okta-core/pull/39253
