### ISSUE TITLE
okta logo not centered in header

### ISSUE THREAD

**Issue by edburyenegren-okta** [okta/odyssey#306]
The logo in the main navigation is not optically centered to the bar it's contained in.

issue 3: https://oktawiki.atlassian.net/wiki/spaces/UX/pages/751567447/Courage+Re-style+Admin+Adoption+Issues+for+Shared+Code

**Comment by edburyenegren-okta** [comment]
<img width="1552" alt="Screenshot 2020-01-08 16 31 24" src="https://user-images.githubusercontent.com/36284167/72027552-5725ba80-3234-11ea-8f80-f7bac3deb589.png">

This might be the best we can do for now. Not sure why, but this isn't an SVG or even an img. It's an icon font...

How you feel, @joejezowski-okta?

**Comment by joejezowski-okta** [comment]
Better for sure.

**Comment by joejezowski-okta** [comment]
Just wanted to add this image of a variant without the CTA for the record.

<img width="1552" alt="screenshot_2020-01-08_16 37 34" src="https://user-images.githubusercontent.com/49886075/72028255-b08ee900-3236-11ea-918c-806e9afbe3b6.png">

**Comment by edburyenegren-okta** [comment]
https://github.com/okta/okta-core/pull/39253
