### ISSUE TITLE
super header should be smaller than main header

### ISSUE THREAD

**Issue by edburyenegren-okta** [okta/odyssey#307]
Above the main navigation bar is a smaller sub-navigation known as the "Super header". In the restyle effort, the color was changed and the font size caused the height to grow.

Needs updating to more accurately match what existed.

@joejezowski-okta should we drop the font size or the padding?

issue 4: https://oktawiki.atlassian.net/wiki/spaces/UX/pages/751567447/Courage+Re-style+Admin+Adoption+Issues+for+Shared+Code

**Comment by joejezowski-okta** [comment]
I think we'll be good shortening the padding (for a11y compliance). Here I have it at 36px tall:
https://www.figma.com/file/WuoOmEdJvabFJVMJrUrg26/Admin-Header-Copy?node-id=0%3A1

I think plan B is to reduce font size to "body text two".

Let me know if that works!

**Comment by edburyenegren-okta** [comment]
Padding reduced!

<img width="1552" alt="Screenshot 2020-01-08 12 35 11" src="https://user-images.githubusercontent.com/36284167/72013738-529cda00-3213-11ea-97d5-6305385128bd.png">

**Comment by johnintrater-okta** [comment]
IMO this still feels too prominent. @joejezowski-okta do you think we should also shrink the font size as well?

**Comment by joejezowski-okta** [comment]
@edburyenegren-okta @johnintrater-okta yea, I think it should drop down to `body text 2`

**Comment by edburyenegren-okta** [comment]
<img width="1552" alt="Screenshot 2020-01-08 15 27 00" src="https://user-images.githubusercontent.com/36284167/72024858-605e5980-322b-11ea-9764-4b727de051a7.png">

@johnintrater-okta @joejezowski-okta thoughts?

**Comment by johnintrater-okta** [comment]
@edburyenegren-okta better but now the padding looks too large, don't you think @joejezowski-okta?

**Comment by joejezowski-okta** [comment]
I don't think it's bad. Hierarchy is pretty clear to me. @johnintrater-okta

**Comment by edburyenegren-okta** [comment]
https://github.com/okta/okta-core/pull/39253
