### ISSUE TITLE
“My apps” in main header needs padding to accommodate hover state

### ISSUE THREAD

**Issue by edburyenegren-okta** [okta/odyssey#309]
issue 5: The "my apps" link in the upper right corner of the main navigation was flush right after the re-style effort. When you hover over it, the state makes it visually squished. It needs more spacing.

**Comment by edburyenegren-okta** [comment]
<img width="163" alt="Screenshot 2020-01-08 13 38 07" src="https://user-images.githubusercontent.com/36284167/72018271-33ef1100-321c-11ea-8e9a-82cc1c6acc63.png">

Updated the spacing to account for the icon size as well

**Comment by joejezowski-okta** [comment]
Looks good. Just to double check…I noticed that the component would change when the browser window changed size. Did you look at that?

**Comment by edburyenegren-okta** [comment]
https://github.com/okta/okta-core/pull/39253
