### ISSUE TITLE
Page titles need to be an Odyssey title size and weight

### ISSUE THREAD

**Issue by edburyenegren-okta** [okta/odyssey#310]
The font size used for page titles was far too large. Needs updating to:

ms(3) at 600 weight

**Comment by edburyenegren-okta** [comment]
<img width="1050" alt="Screenshot 2020-01-08 14 01 08" src="https://user-images.githubusercontent.com/36284167/72019856-55053100-321f-11ea-9b23-ed057684e11d.png">

@joejezowski-okta thoughts?

**Comment by joejezowski-okta** [comment]
Awww yea. Looks good to me!

**Comment by edburyenegren-okta** [comment]
https://github.com/okta/okta-core/pull/39253
