### ISSUE TITLE
Footer content linebreaks

### ISSUE THREAD

**Issue by edburyenegren-okta** [okta/odyssey#311]
Global body copy grew to 16px which caused the text to wrap in the footer container. The container needs to be widened to avoid wrapping.

Possibly drop to `ms(-1)` and $text-sub

**Comment by edburyenegren-okta** [comment]
<img width="1159" alt="Screenshot 2020-01-08 13 44 09" src="https://user-images.githubusercontent.com/36284167/72018683-f5a62180-321c-11ea-986d-dbf50498f4c2.png">

applied style recs from @joejezowski-okta and removed max-width on footer paragraphs

**Comment by joejezowski-okta** [comment]
It looks like the "Albatross Local Development" may be another color than the rest of the items. Do you know if there are any feature flags that might put different content here?

**Comment by edburyenegren-okta** [comment]
https://github.com/okta/okta-core/pull/39253

**Comment by edburyenegren-okta** [comment]
@joejezowski-okta it's because it isn't a link
