### ISSUE TITLE
"get started" should have a visible arrow

### ISSUE THREAD

**Issue by edburyenegren-okta** [okta/odyssey#317]
issue 17

**Comment by joejezowski-okta** [comment]
@edburyenegren-okta I don't see a reference for this issue anymore in the wiki

**Comment by LanaChoi-okta** [comment]
is this the getting started page youre referring to? https://design-system-admin.trexcloud.com/admin/getting-started

unsure where the arrow is or where the arrow is supposed to be

**Comment by LanaChoi-okta** [comment]
I'm okay with removing the arrow altogether. It doesn't seem like it hurts the page to not have it
