### ISSUE TITLE
Select/dropdown; "gear button" color and spacing

### ISSUE THREAD

**Issue by edburyenegren-okta** [okta/odyssey#321]
issue 21

**Comment by joejezowski-okta** [comment]
See number #15 by @LanaChoi-okta in [Shared items](https://oktawiki.atlassian.net/wiki/spaces/UX/pages/751567447/Courage+Re-style+Issues):

**Comment by edburyenegren-okta** [comment]
Just confirmed this issue also isn't coming from our shared files. The width is being set manually on the element.
