### ISSUE TITLE
Table design issue - button doesn't fit in table header

### ISSUE THREAD

**Issue by johnintrater-okta** [okta/odyssey#329]
RSA / On Prem : No space between button and border 

![4ec4bde1-8bc9-4d7d-a28b-4102df88db65](https://user-images.githubusercontent.com/25807702/71846367-5ce69900-3098-11ea-8b35-bf1df77f9025.png)
(need to change header padding)

**Comment by joejezowski-okta** [comment]
Also make "Inactive" button Select/dropdown have grey border

**Comment by joejezowski-okta** [comment]
Might need to override header height to accommodate button
