### ISSUE TITLE
Table bug - Yubikey section; Browse input field bug, "Find Yubikey" input

### ISSUE THREAD

**Issue by johnintrater-okta** [okta/odyssey#331]
Yubikey serial number fields and find Yubikey should look better

![bc0cdd68-5100-410c-89bf-da870ae7d532](https://user-images.githubusercontent.com/25807702/71846499-b9e24f00-3098-11ea-9cf4-bf1068765d14.png)

**Comment by joejezowski-okta** [comment]
"Find Yubikey" button should have grey border
