### ISSUE TITLE
Spacing bug - Application graphic placeholder; Edit icon (See #1)

### ISSUE THREAD

**Issue by johnintrater-okta** [okta/odyssey#333]
icon is shifted. 

![cd80d4c1-b547-4516-be5e-b12ee49eb17f](https://user-images.githubusercontent.com/25807702/71846604-fca42700-3098-11ea-833e-870d4029cc71.png)
see #1

**Comment by edburyenegren-okta** [comment]
just confirmed that these styles _aren't_ shared, so closing and removing.
