### ISSUE TITLE
Spacing bug - Application graphic placeholder  (See #2)

### ISSUE THREAD

**Issue by johnintrater-okta** [okta/odyssey#334]
spacing at the bottom is less than the top.

see #2

![cd80d4c1-b547-4516-be5e-b12ee49eb17f](https://user-images.githubusercontent.com/25807702/71846653-17769b80-3099-11ea-912c-7db2ce9eadaa.png)

**Comment by joejezowski-okta** [comment]
Remove overrides, apply Odyssey spacing to even out. Use closest neighbor, either 12px or 24px unit

**Comment by edburyenegren-okta** [comment]
Another one that doesn't actually come from shared code. Closing and removing.
