### ISSUE TITLE
Select/dropdown bug (See #3)

### ISSUE THREAD

**Issue by johnintrater-okta** [okta/odyssey#335]
Active button looks messed up see #3

![cd80d4c1-b547-4516-be5e-b12ee49eb17f](https://user-images.githubusercontent.com/25807702/71846703-34ab6a00-3099-11ea-80c5-adddb50be13c.png)

**Comment by joejezowski-okta** [comment]
Also change border color to grey

**Comment by edburyenegren-okta** [comment]
Just confirmed that this is coming from an inline style, not shared code.
