### ISSUE TITLE
Small box looks messed up 

### ISSUE THREAD

**Issue by johnintrater-okta** [okta/odyssey#336]
Small box looks messed up 

![cd80d4c1-b547-4516-be5e-b12ee49eb17f](https://user-images.githubusercontent.com/25807702/71846759-54429280-3099-11ea-98b7-bd354a54b783.png)

**Comment by joejezowski-okta** [comment]
This needs a clearer description. 

Shared issues I see:
- Search box w/select
- Table button alignment
- Table button colors
- Select border color
- Select button size

**Comment by joejezowski-okta** [comment]
@johnintrater-okta Do you know what the "Small box" is here?

**Comment by edburyenegren-okta** [comment]
another one that doesn't belong to us
