### ISSUE TITLE
Select/Dropdowns; Active and inactive policies and policy rules

### ISSUE THREAD

**Issue by johnintrater-okta** [okta/odyssey#339]
Active and inactive policies and policy rules. Activate and deactivate policies and policy rules.

![6e87a6e6-d015-402d-92b8-8f3e188d83ea](https://user-images.githubusercontent.com/25807702/71846936-ba2f1a00-3099-11ea-840c-d6363f9677b4.png)

**Comment by joejezowski-okta** [comment]
Select menu's should have grey borders
Buttons with icons only should have grey borders

**Comment by edburyenegren-okta** [comment]
fixed
