### ISSUE TITLE
Nim removes numbers/bullets on ordered/unordered lists

### ISSUE THREAD

**Issue by joejezowski-okta** [okta/odyssey#34]
Looks like some overzealous rules in _reset.scss.

**Comment by joejezowski-okta** [comment]
@edburyenegren-okta What is this? Should we close?

**Comment by edburyenegren-okta** [comment]
I believe this was fixed by https://github.com/okta/odyssey/blob/4d207c8ffed8d90c8aa317f33ca5b22505a5376c/src/scss/base/_typography.scss#L83-L107
