### ISSUE TITLE
Table button - Alignment and border colors

### ISSUE THREAD

**Issue by johnintrater-okta** [okta/odyssey#340]
The dismiss button is not aligned vertically

![5a8a6208-e203-4fd1-a62f-e51170893c0a](https://user-images.githubusercontent.com/25807702/71846972-cdda8080-3099-11ea-8dd8-4bed620d9ebd.png)

**Comment by joejezowski-okta** [comment]
Specifically the "Dismiss" button:

- Align vertically to row
- Change border color to grey
