### ISSUE TITLE
Select/Dropdown bug - Hover background color off

### ISSUE THREAD

**Issue by johnintrater-okta** [okta/odyssey#341]
Dropdown hover CSS off

![b4eaf579-8ea8-4fe0-bc6a-a09d0011382c](https://user-images.githubusercontent.com/25807702/71847004-ec407c00-3099-11ea-82a6-9371e19f2c0c.png)
![655d0f8f-6dcd-4408-9361-ee509b03d07f](https://user-images.githubusercontent.com/25807702/71847005-ec407c00-3099-11ea-99ba-c6038598df71.png)

**Comment by joejezowski-okta** [comment]
Some selects remain highlighted after values are changed
Hover state in dropdown extends beyond the border
