### ISSUE TITLE
Invisible datalist message for empty result

### ISSUE THREAD

**Issue by jhe-okta** [okta/odyssey#344]
When a datalist contains no result, it shows some message underneath the binary logo. But with Odyssey, the text is set to #fffff in .data-list-head which is the same as the background color.

## Detailed description

> Is this issue related to a specific component?
   Datalist

> What did you expect to happen? What happened instead?

> What browser & version are you experiencing this in?

## Steps to reproduce the issue

1. Step one.
2. Step two.
3. Step three.
4. Bug!

## Screenshots

before
![Screen Shot 2020-01-17 at 12 30 12 PM](https://user-images.githubusercontent.com/5066836/72644130-237a1d00-3925-11ea-9d66-c7d3bb62a1cc.png)
after
![Screen Shot 2020-01-17 at 12 24 02 PM](https://user-images.githubusercontent.com/5066836/72644128-237a1d00-3925-11ea-8ecc-1938afc2b866.png)

**Comment by edburyenegren-okta** [comment]
Closing as this is unrelated to ODS

however, ODS does provide an empty table pattern: https://design-docs.trexcloud.com/components/table.html#empty-tables
