### ISSUE TITLE
Banner

### ISSUE THREAD

**Issue by johnintrater-okta** [okta/odyssey#348]
- [ ] Design
- [ ] Design Docs
- [ ] Dev
- [ ] Dev Docs

**Comment by FeliciaWang-okta** [comment]
@edburyenegren-okta cool - thanks for clarifying.

Alerts would definitely be helpful for us in a whole variety of different experiences :)

**Comment by alexdahl-okta** [comment]
OIN Manager may be interested. We are definitely interested in communicating things like "action required" and "no going back after this".
