### ISSUE TITLE
Blockquote

### ISSUE THREAD

**Issue by johnintrater-okta** [okta/odyssey#349]
>The HTML `<blockquote>` Element (or HTML Block Quotation Element) indicates that the enclosed text is an extended quotation. Usually, this is rendered visually by indentation (see Notes for how to change it). A URL for the source of the quotation may be given using the cite attribute, while a text representation of the source can be given using the `<cite>` element.

**Comment by joejezowski-okta** [comment]
@edburyenegren-okta Do we have any examples of this being used in product? I'd imagine this would be helpful for marketing folks.

**Comment by edburyenegren-okta** [comment]
It's not super common in product. Sometimes Callouts will include quoted text from docs. The styling today is similar to common patterns: border on the left, some extra padding.

**Comment by LanaChoi-okta** [comment]
are we prioritizing this for marketing? unless they really need it i feel like this should be deprioritized

**Comment by edburyenegren-okta** [comment]
@LanaChoi-okta we are trying to ship some non-component styling every month. They go pretty quickly because they aren't full components, but folks tend to use them more than they think.

e.g. Admin currently uses blockquotes when citing text from documentation in callouts.

**Comment by alexdahl-okta** [comment]
Developer blogs posts would like guidance here, though their path to Odyssey adoption is unclear. (They are separate from docs.)

<img width="973" alt="Screen Shot 2020-03-06 at 4 34 06 PM" src="https://user-images.githubusercontent.com/26014482/76135156-776dbd80-5fc8-11ea-8767-ded61ae5c244.png">
<hr>
<img width="938" alt="Screen Shot 2020-03-06 at 4 34 28 PM" src="https://user-images.githubusercontent.com/26014482/76135158-7a68ae00-5fc8-11ea-9b3b-9dd0a65ff139.png">

Dev docs would like guidance on when to use blockquotes versus other kinds of callouts or pullquotes.

**Comment by hor-kanchan-okta** [comment]
Sorry, I clicked the close button by accident.

**Comment by edburyenegren-okta** [comment]
Closed by https://github.com/okta/odyssey/pull/435
