### ISSUE TITLE
Multi-Select

### ISSUE THREAD

**Issue by joejezowski-okta** [okta/odyssey#36]
**Summary**
Figma:
- [x] New input with dropdown icon
- [x] Create "system style" dropdown menu
- [x] Create "custom style" dropdown menu
- [x] Create custom style dropdown menu with checkboxes.
- [x] Implement with AutoLayout

So far, some exploration work has been done on Selects and Multi-Selects.

With so many behavior/use case combinations available, we ought to treat these inputs to their design cycle.

Some items for consideration:

which library to use

support for browser-default select and multi-select (no library)

when to use each

display of long mult-select item lists

where/how to remove items from a list

**Comment by jeffbelser-okta** [comment]
:100: This is one of the variants we identified as being critical for UI Core! I would vote for having this expressed as a variant to the existing `Select` component and its interface!

**Comment by joejezowski-okta** [comment]
@edburyenegren-okta 

Design explorations:
https://www.figma.com/file/x7qqY6wlae0slfWmoEDx8q/Multi-Select?node-id=1%3A3
