### ISSUE TITLE
Description Lists

### ISSUE THREAD

**Issue by johnintrater-okta** [okta/odyssey#360]
>The HTML `<dl>` element represents a description list. The element encloses a list of groups of terms (specified using the `<dt>` element) and descriptions (provided by `<dd>` elements). Common uses for this element are to implement a glossary or to display metadata (a list of key-value pairs).

>The HTML `<dt>` element specifies a term in a description or definition list, and as such must be used inside a `<dl>` element.

>The HTML `<dd>` element provides the description, definition, or value for the preceding term (`<dt>`) in a description list (`<dl>`).

**Comment by alexdahl-okta** [comment]
Dev docs will probably use this.

**Comment by edburyenegren-okta** [comment]
Bundling with #386 and #396

@alexdahl-okta, i'll ping you on the review - we probably won't provide specific key/value styling on this round, but would love feedback based on your needs
