### ISSUE TITLE
Nim: Allow overriding variables

### ISSUE THREAD

**Issue by joejezowski-okta** [okta/odyssey#37]
It'd be nice to use !default in declarations in _variables.scss and _colors.scss. This would fix issues such as Proxima Nova 404s (by letting us override the body font family) and low contrast body text (by letting us override $text-body).

**Comment by alexdahl-okta** [comment]
Related: #8.

Dev docs was bitten by this, the workaround is painful: https://github.com/okta/okta-developer-docs/pull/536/files

I expect we eventually want `!default` on all variables.

**Comment by mattkaniaris-okta** [comment]
> I expect we eventually want !default on all variables.

Yes!
