### ISSUE TITLE
Horizontal rule

### ISSUE THREAD

**Issue by johnintrater-okta** [okta/odyssey#371]
>The HTML `<hr>` element represents a thematic break between paragraph-level elements: for example, a change of scene in a story, or a shift of topic within a section.

**Comment by alexdahl-okta** [comment]
Dev docs and OIN manager would probably appreciate guidance on when to use an `<hr>` versus a border on another UI element. But not a burning priority.

**Comment by joejezowski-okta** [comment]
We need to ensure that these get resurfaced somehow for figma docs.
