### ISSUE TITLE
Keyboard

### ISSUE THREAD

**Issue by johnintrater-okta** [okta/odyssey#376]
>The HTML Keyboard Input element (`<kbd>`) represents a span of inline text denoting textual user input from a keyboard, voice input, or any other text entry device.

**Comment by alexdahl-okta** [comment]
Oh interesting.

Dev docs includes a lot of inline code snippets:

<img width="644" alt="Screen Shot 2020-03-06 at 4 45 04 PM" src="https://user-images.githubusercontent.com/26014482/76135308-df70d380-5fc9-11ea-86aa-989a4a7a2741.png">

Today they are `<code>`, which is tracked as #353. (We also have block code examples, which today are `<pre>`. Tracked as #386.)

Guidance would be appreciated on when we should use `<kbd>`, `<code>`, or `<pre>`.

Some of our inline code snippets probably qualify as `<kbd>`: we have lots of instructions telling the user to use some text. But plenty are not necessarily user input.
