### ISSUE TITLE
Select

### ISSUE THREAD

**Issue by johnintrater-okta** [okta/odyssey#391]
>The HTML `<select>` element represents a control that provides a menu of options

- [x] Inventory
- [x] Research
- [x] Explore
- [x] Create
- [x] Document
- [ ] Release

**Figma File:**
Figma:
https://www.figma.com/file/KYOpuRHdCykocQYoxptvSu/Inputs?node-id=3%3A839

**Comment by alexdahl-okta** [comment]
Dev docs looks forward to `select`s.

We have a couple components that could use guidance here.

An in-page navigation menu in narrow viewports, which is a simple "pick and go" input:
<img width="411" alt="content-nav" src="https://user-images.githubusercontent.com/26014482/76135015-31642a00-5fc7-11ea-84f5-89f6ddf623cd.png">

An in-page content selector, which desires more power such as icons and filtering:
<img width="670" alt="stack-selector" src="https://user-images.githubusercontent.com/26014482/76135017-35904780-5fc7-11ea-8f27-1985dfa56b99.png">

(Variations on them are live today, but these are dirty mockups.)

It'd be great to have guidance on whether these should be `select`, or if they should be some other menu component.

**Comment by edburyenegren-okta** [comment]
Office Hours notes 3/10: 

- async and local load
- a11y
- HTML/CSS only version
- search/filter through options
- no dependency on jquery (ideally standalone)
- custom templates (selectize)

**Comment by joejezowski-okta** [comment]
@edburyenegren-okta Any word on whether we can have Selects switch to the slot machine UI on mobile devices with Selectize?
