### ISSUE TITLE
Typographical Modifiers

### ISSUE THREAD

**Issue by johnintrater-okta** [okta/odyssey#397]
>The HTML Superscript element (`<sup>`) specifies inline text which is to be displayed as superscript for solely typographical reasons.

>The HTML Subscript element (`<sub>`) specifies inline text which should be displayed as subscript for solely typographical reasons.

>The HTML Strong Importance Element (`<strong>`) indicates that its contents have strong importance, seriousness, or urgency. Browsers typically render the contents in bold type.

>The HTML `<s>` element renders text with a strikethrough, or a line through it. Use the `<s>` element to represent things that are no longer relevant or no longer accurate. However, `<s>` is not appropriate when indicating document edits; for that, use the `<del>` and `<ins>` elements, as appropriate.

>The HTML `<small>` element represents side-comments and small print, like copyright and legal text, independent of its styled presentation. By default, it renders text within it one font-size smaller, such as from small to x-small.

>The HTML Mark Text element (`<mark>`) represents text which is marked or highlighted for reference or notation purposes, due to the marked passage's relevance or importance in the enclosing context.

>The HTML `<em>` element marks text that has stress emphasis. The `<em>` element can be nested, with each level of nesting indicating a greater degree of emphasis.

**Comment by edburyenegren-okta** [comment]
Closed by https://github.com/okta/odyssey/pull/435
