### ISSUE TITLE
Product Emails

### ISSUE THREAD

**Issue by joejezowski-okta** [okta/odyssey#421]
### Summary

Research emails that are generated by our email systems. Run through our process and create components to build out email design system.

### MVP functionality

What functionality would be required for an initial release?

### Timeline / Project

Is this request related to an upcoming release or project?

**Comment by alexdahl-okta** [comment]
+1 to transactional email support (account created, etc).

Also +1 to general email guidance. We have a variety of newsletters and nuture campaigns that would benefit from the same components, as well as some different (?) layout guidance.
