### ISSUE TITLE
Step progress indicator

### ISSUE THREAD

**Issue by alexdahl-okta** [okta/odyssey#424]
### Summary

Wizards are likely a large, template-level topic – so to start, I'm scoping this to a step progress indicator.

As part of a guided flow, the system should communicate how many steps are in the flow and which step is current.

For example, in the Admin Console today:
<img width="1013" alt="steps" src="https://user-images.githubusercontent.com/26014482/76474339-701b2b00-639f-11ea-9ffc-045538935442.png">

This is probably the best-fit use case. Today's component also has the ability to indicate sub-step progress and step error states.

OIN Manager also uses this pattern to communicate a longer-term (days to weeks) business process:
<img width="300" alt="process" src="https://user-images.githubusercontent.com/26014482/76474408-afe21280-639f-11ea-9ceb-a8e898c19a01.png">

More distantly, a similar component may be desired to indicate the progress of system jobs (such as user import). But that's much more speculative.

To me, the need to communicate _steps_ makes this component distinct from a task progress bar (#74) or meter (#381). But overlap with a task progress bar deserves consideration.

Carbon and Lightning simply call this "Progress Indicator":
- https://www.carbondesignsystem.com/components/progress-indicator/code
- https://lightningdesignsystem.com/components/progress-indicator/

### MVP functionality

Perhaps:
- Show all steps
- Number and name for steps
- Indication of complete steps
- Indication of current step

### Timeline / Project

Not related to an upcoming release or project.

cc @LanaChoi-okta

**Comment by LanaChoi-okta** [comment]
yesss i am upvoting this!

**Comment by LanaChoi-okta** [comment]
also tagging @jessicaallen-okta who uses a similar pattern in her import jobs page
