### ISSUE TITLE
Release 0.1.2

### ISSUE THREAD

**Issue by joejezowski-okta** [okta/odyssey#436]
This issue entails everything we need to do on release day.

**Communication**
- [x] Notify Design Slack Channel
- [x] Notify Odyssey Slack Channel
- [x] Push info on next newsletter

**Eng**
- [x] Update package version
- [x] Github release (includes release notes)
- [x] Publish NPM package & Docs

**Design**
- [x] Push table UIs to Odyssey UI Kit 
- [x] Push select UI's to Odyssey UI Kit
- [x] Push Doc updates to Odyssey UI Kit

**Comment by joejezowski-okta** [comment]
**Communication**
- [ ] Notify Design Slack Channel
- [ ] Notify Odyssey Slack Channel
- [ ] Push info on next newsletter

**Eng**
- [ ] Update package version
- [ ] Github release (includes release notes)
- [ ] Publish NPM package & Docs

**Design**
- [ ] Push table UIs to Odyssey UI Kit 
- [ ] Push select UI's to Odyssey UI Kit
- [ ] Push Doc updates to Odyssey UI Kit

**Comment by johnintrater-okta** [comment]
This is really great @joejezowski-okta. A couple of additional thoughts:
- should we include slides for the next SotU?
- what about notifying key eng slack channels?  
- do we want to drive any questions/comments/concerns to a specific place (like opening a ticket, messaging on #odyssey slack etc?)

**Comment by joejezowski-okta** [comment]
- @johnintrater-okta  I was questioning adding the newsletter portion and SoTU to this ticket because I feel like the issue will roll on until those things get completed (which will typically not coincide with a release). I do think they should happen though…I'm pretty confident we'll communicate in those channels regardless of it being an issue or not.
- I'm open to more eng-channels, I'll leave that up to @edburyenegren-okta and @arnoldsandoval-okta though. 
- Can definitely add this messaging to the release message
- I'd rather drive people to our actual docs site (single source of truth) vs multiple locations. Also less to manage.

**Comment by johnintrater-okta** [comment]
Re: newsletter and SoTU I totally agree. We should do some legwork upfront to get things prepped and ready so when the time comes the work is done but also ok with just doing it when we need it.
