### ISSUE TITLE
Buttons

### ISSUE THREAD

**Issue by joejezowski-okta** [okta/odyssey#44]
**Figma**

- [x] Usage page
- [x] Primary
- [x] Secondary
- [x] Caution
- [x] Size: Default
- [x] Size: Small
- [x] Focus state
- [x] Hover
- [x] Clear buttons
- [x] Contains Icon
- [x] Investigate padding and text size

Reference JIRA: 
https://oktainc.atlassian.net/browse/UX-2015?jql=component%20%3D%20%22Design%20System%22%20AND%20status%20!%3D%20Done

**Comment by edburyenegren-okta** [comment]
Do we want to ship with all of the above variants in the MVP?

**Comment by joejezowski-okta** [comment]
@edburyenegren-okta 

You have almost everything built here with the exception of the edits we've discussed and the "contains icon" button.

**Comment by edburyenegren-okta** [comment]
For "contains icon" I'm guessing we'll just need to standardize on margin-from-copy and ensure the SVGs display correctly on web?
