### ISSUE TITLE
[docs] List all available components in side-nav

### ISSUE THREAD

**Issue by jmelberg-okta** [okta/odyssey#455]
### Summary

All **styled** components should be listed in the side navigation in the design-docs. It appears we are missing the following completed/in progress components:

- Banner
- Callout
- Card
- Dropdown (In progress)
- Meter
- Navigation (In progress)
- Number Input
- Switch
- Toast
- Top Bar (In progress)

**Comment by mattkaniaris-okta** [comment]
It would also be nice to put the status of each component on their respective pages instead of a table on a different page.

**Comment by johnintrater-okta** [comment]
This is a great idea @mattkaniaris-okta. @arnoldsandoval-okta is leading the evolution of the Odyssey docs so we will take this into consideration as we iterate. (cc @joejezowski-okta)

**Comment by jmelberg-okta** [comment]
Resolved with #520
