### ISSUE TITLE
Apply Rebrand Color to Odyssey

### ISSUE THREAD

**Issue by edburyenegren-okta** [okta/odyssey#474]

**Comment by joejezowski-okta** [comment]
@edburyenegren-okta @johnintrater-okta @nickarcidy-okta We need to properly scope this. 

One thing to note that we haven't yet discussed…there are changes to the color scale as it pertains to the numbers and values associated to them. In particular the neutral/gray values only going to 100-500 vs. 0-900. Designers and engineers are used to the current scale (especially from the Courage Refactor project) and will need some guide or training on what the new values are. I don't think it'd serve us well to just hand them off.

**Comment by johnintrater-okta** [comment]
@joejezowski-okta I hear that. Why don’t you schedule time for us to discuss so we can work through it together before you get too deep.

**Comment by nickarcidy-okta** [comment]
Great point @joejezowski-okta . Happy to educate everyone impacted. Also a suggestion would be to pivot from the 'hundred' convention altogether, and go with something totally different, like Gray 1 through Gray 5. Also, in our last meeting you had mentioned that you were going to take a closer look at the Figma and let me know if there was anything else you needed to assist in the handoff to Odyssey. I'm here to take this across the finish line if there's anything else you need from my end.

**Comment by edburyenegren-okta** [comment]
@joejezowski-okta @nickarcidy-okta closing this as the first round of work is done. We can finalize via https://github.com/okta/odyssey/issues/530
