### ISSUE TITLE
Suggestion: Radio components should have dynamic sizing rather than fixed

### ISSUE THREAD

**Issue by stevennguyen-okta** [okta/odyssey#497]
### Summary

Currently, the radio components have 442 width no matter the label string length. This breaks my expectation for a component to be dynamically sized based on the content (in most cases).
Resizing the component doesn't help because the text sub-element has a fixed width that still gets caught in drag-selection.

![radio](https://user-images.githubusercontent.com/39841526/80422489-14dfc200-8893-11ea-9344-db567978fcae.gif)

### MVP functionality

The radio component's sizing should dynamically match the combination of the radio and the length of the label if possible. Or at the very least adjusts based on resizing.

### Timeline / Project

Nope

**Comment by edburyenegren-okta** [comment]
Fixed!
