### ISSUE TITLE
contrast on text

### ISSUE THREAD

**Issue by joejezowski-okta** [okta/odyssey#50]
Contrast on text throughout Nim is too low. Technically, it meets the W3C level AA guideline of 4.5:1 contrast ratio, but: 

1. 4.5:1 is the bare minimum. The W3C recommends 7:1. 2. Not everyone has perfect eyesight. This is especially true for older users.3. Users often work in environments with glare (outside), or have their screen dimmed to save battery life, or have terrible monitors like engineers at okta.4. The W3C contrast guidelines are based on research from 1998, when office lighting was dimmer and screens were CRTs with 10,000:1 contrast ratios. Modern LCDs are lucky to get 900:1. 

Body text is currently gray 700: #5c6971.  Moving to gray 800: #46545e would technically meet the recommendation, but I'd argue less is not more - we should not attempt to thread the needle on legibility.  Closer to the current gray 900: #2f3f4a would likely be vastly better for the majority of our users.

**Comment by joejezowski-okta** [comment]
Geoff Greer:

"I'd recommend going with #333 or #222. The nim grays have a blue hue, which to me seems odd for body text."


Edbury Enegren:

"Geoff Greer mixing in a hue is pretty common for text shades, but we could still achieve a higher contrast ratio regardless.

Nick Arcidy Todd Matthews Candidate for November?"

**Comment by alexdahl-okta** [comment]
Related: #18.

**Comment by edburyenegren-okta** [comment]
Closing this: colors are set / a11y isn't a forcing function for now.
