### ISSUE TITLE
External visited link "new window" icon is default link color

### ISSUE THREAD

**Issue by arnoldsandoval-okta** [okta/odyssey#505]
## Detailed description

While debugging #19 I noticed that external visited links match the default link color (blue) when instead they should be the visited link color (purple).

This occurs in pretty much all browsers.

1. Make a link with the `target="_blank"` and `rel="noopener"` attributes
2. Click it
3. The link color does not match the icon color

## Screenshots
![image](https://user-images.githubusercontent.com/62259644/80447491-5f326480-88ce-11ea-929d-04b007e2cf5c.png)

**Comment by alexdahl-okta** [comment]
2¢: if possible, it would be great if the icon color inherited whatever the link color is.

Visited links are certainly the most prominent issue. Any perhaps Odyssey wishes to discourage other link colors.

But I anticipate scenarios in dev docs where we have white link text on dark backgrounds, or currently have special magenta branding applied to some links, etc. It'd be great if the icon inherited whatever the link color is, and we didn't have to make lots of overrides.

**Comment by arnoldsandoval-okta** [comment]
This is solid feedback @alexdahl-okta, I agree. I'll take a look and see what we can do with our existing icon implementation.

We're tackling high-level icons soon. This is a case to consider should we revise our technical implementation.

**Comment by edburyenegren-okta** [comment]
After some investigation, this is going to require a more significant rework.

There appears to be a cross-browser bug when styling pseudo-elements - they don't respect any overriding or specific styles after the initial object has been styled:

<img width="1216" alt="Screenshot 2020-07-08 11 29 19" src="https://user-images.githubusercontent.com/36284167/86965261-18f25080-c11c-11ea-8323-e675e790fbf1.png">
<img width="1231" alt="Screenshot 2020-07-08 11 29 02" src="https://user-images.githubusercontent.com/36284167/86965271-1d1e6e00-c11c-11ea-9219-8f896ce38dde.png">

team members can view more context here: https://okta.slack.com/archives/C7KV3NLE8/p1594233529265800
