### ISSUE TITLE
Combinators and Encapsulation

### ISSUE THREAD

**Issue by mattkaniaris-okta** [okta/odyssey#533]
### Summary
Sibling and Adjacent CSS combinators fundamentally break encapsulation and are often fail deadly:  encapsulated components can not depend on the correct behavior of siblings which they do not control by definition.  Highly proscriptive markup makes adoption harder than necessary and tends to break whatever is not explicitly supported out of the box.  The ASA code base has no usages of `~` and one `+`.  The Azuqua designer code base (~16KloC SCSS) has 10 usages of `~`.  We avoid using these bits of CSS because we can't use them safely. 

By way of example, the React-Odyssey bindings define a `FieldSet` component like:

```TSX

import classNames from 'classnames';

export type ExtraFieldSetProps = {
  aside?: ReactNode;
  error?: ReactNode;
  isFlex?: boolean;
  label?: ReactNode;
  legend?: ReactNode;
  optional?: boolean;
};

export type FieldSetProps = ComponentProps<'fieldset'> & ExtraFieldSetProps;
export const FieldSet = ({ legend, htmlFor, label, aside, children, error, optional, className, isFlex=true, ...rest }: FieldSetProps) =>
  <fieldset className={classNames('ods-fieldset', className)} {...rest}>
    <div className={classNames({ 'ods-fieldset-flex': isFlex, error })}>
      { legend && <Legend>{ legend }</Legend> }
      { label && <Label htmlFor={htmlFor} optional={optional}>{ label }</Label>}
      { aside && <Aside isHint>{ aside }</Aside> }
      { children }
      { error && <Aside isError>{ error }</Aside> }
    </div>
  </fieldset>;
```
The `FieldSet` optionally takes a legend, label, hint, or error in addition to `children` (which can be any number of valid ReactElements).  `FieldSet` is modular - it does not know or care what what exactly goes in a label (or doesn't), what children it may render, nor do its children know or care what what other things the `FieldSet` may do beyond what it's interface describes.  It is used like so:

```TSX
<FieldSet label="input">
  <input type="text" />
</FieldSet>
<FieldSet label="textarea">
  <textarea />
</FieldSet>
<FieldSet label="Autocomplete and SomeOtherInput" optional={false}>
  <Autocomplete />
  <SomeOtherInput />
</FieldSet>
```

This code compiles, passes lint, and likely passes tests regardless of the UX actually being usable by a human.  A dev can't look at this and know if it works without looking up the definition of `Autocomplete`  and `SomeOtherInput` (broken encapsulation).  In turn, `Autocomplete`, can only be used in a very specific context which isn't captured in code or by the type system (broken composability).  Odyssey's treatment of [labels](https://github.com/okta/odyssey/blob/master/packages/odyssey/src/scss/components/_label.scss#L15) and related components is both fail deadly and highly unidiomatic for React.

### MVP functionality
I'd propose that Odyssey carefully consider all existing usage of adjacent/general sibling combinators with an eye on modularity.  If it turns out that this sort of coupling is a hard requirement of legacy apps that directly mutate the DOM,  perhaps Odyssey could move this behavior behind a switch or support a different class for that use case.  Alternatively, Odyssey could support a different class for component based SPAs so they have some way of specifying the behavior they want via CSS classes alone (minimal usage of all combinators/closer to BEM).

**Comment by alexdahl-okta** [comment]
Do you have an example of a specific instance? What's the HTML output for a field set with `Autocomplete`?

**Comment by mattkaniaris-okta** [comment]
Autocompletes have a div or two around the `input`.  Off the top of my head, Odyssey's `Checkboxes` and `Radios` are fail deadly if the markup is wrong (drop the ID or mess it up).  I think its OK for styling to be wrong in that case, but not for the inputs to not work.  The optional labels will just disappear.
