### ISSUE TITLE
Styled Elements in Figma

### ISSUE THREAD

**Issue by edburyenegren-okta** [okta/odyssey#539]
Add Styled Elements to Figma docs/symbols

**Comment by joejezowski-okta** [comment]
@arnoldsandoval-okta @edburyenegren-okta 

As I dig into this, a lot of these are either not possible in Figma, or they are just standard options for a designer to select (for example Superscript). Not sure what to do here or if its worth it.

**Comment by joejezowski-okta** [comment]
@arnoldsandoval-okta Please check out the designs here:
https://www.figma.com/file/vVx4JpIRvr8SYnXSG7FSOG/Styled-elements?node-id=25%3A2
