### ISSUE TITLE
Timestamp component

### ISSUE THREAD

**Issue by joejezowski-okta** [okta/odyssey#54]
ScaleFT has a timestamp component, but it could use some design feedback. Currently, it shows the relative time ("3 days ago", "a few seconds ago", "30 days from now", etc), then switches to the absolute time if you click on it ("2018-10-12T20:53:07.972Z"). Showing the relative time is better most of the time, but sometimes it's extremely useful to have an exact timestamp to compare logs against.

The widget was made by me, and I'm not a designer. I'm sure there's some low hanging fruit that could be picked.

![Screenshot_2018-10-15 ScaleFT](https://user-images.githubusercontent.com/49886075/60304959-d898a980-98ef-11e9-8cfe-a2a12b3170f4.png)
![Screenshot_2018-10-15 ScaleFT(1)](https://user-images.githubusercontent.com/49886075/60304960-d9314000-98ef-11e9-9eb9-432963910b76.png)

**Comment by edburyenegren-okta** [comment]
Closing in favor of https://github.com/okta/odyssey/issues/357 (this is older, but that issue has already been slotted into planning)
