### ISSUE TITLE
Tables need a subtitle

### ISSUE THREAD

**Issue by mauriciocastillosilva-okta** [okta/odyssey#547]
### Summary

Table component needs a subtitle that goes right under the Title and before the actual table. Maybe part of the figcaption?

### MVP functionality

subtitle with the corresponding styles

### Timeline / Project

we need this for EA of Recent Activity, which will happen probably July

**Comment by joejezowski-okta** [comment]
@edburyenegren-okta I actually had this designed already. Check it here:

https://www.figma.com/file/Utu5kj6tW2JK0emuWsQfFK/Table?node-id=597%3A4714
