### ISSUE TITLE
32px spacing unit? 

### ISSUE THREAD

**Issue by FeliciaWang-okta** [okta/odyssey#551]
I originally used the 32px spacing unit in form spacing when creating mocks for Admin Restyle. The final version of Odyssey spacing units does not include a 32px option. This isn't a deal breaker for the forms we have today but 32px may come in handy when creating new components or flows in situations for which 24 is too tight and 48 is too big. 

If anyone else comes across use cases for 32px spacing, please let us know in this thread.

**Comment by joejezowski-okta** [comment]
Hey @FeliciaWang-okta just wanted to follow up after doing some ticket grooming with the team. Is this still a concern? We haven't seen many brood use cases or issues brought up by other designers to warrant this yet. If you're cool with it, we were considering closing this issue.
