### ISSUE TITLE
Update $max-line-length for Whyte

### ISSUE THREAD

**Issue by arnoldsandoval-okta** [okta/odyssey#553]
### Summary

We have successfully updated the color, type and spacing, however as a result of our new font-face, we need to re-evaluate `$max-line-length` in tokens.scss

**Comment by edburyenegren-okta** [comment]
Based on character count, our current line-length still works for Whyte + System fonts.

@joejezowski-okta unless you see anything that looks off, I'll close this at the end of our sprint.
