### ISSUE TITLE
Review transition timing and duration

### ISSUE THREAD

**Issue by joejezowski-okta** [okta/odyssey#56]

**Comment by alexdahl-okta** [comment]
Related: #16.

**Comment by edburyenegren-okta** [comment]
@joejezowski-okta what's this a dupe of?

**Comment by edburyenegren-okta** [comment]
Related: https://github.com/okta/odyssey/issues/193

**Comment by joejezowski-okta** [comment]
No code commits, but we reviewed. We will revisit once branding is done.
