### ISSUE TITLE
DateInput

### ISSUE THREAD

**Issue by jeffbelser-okta** [okta/odyssey#562]
### Summary

This library should include an `<o-date-input>` component that accepts date information through a variety of interactions:

* Through an accessible popover calendar UI
* Through manual text entry into the input

This is an important piece of UI looking backward at some of the historical use in Courage UI.

### MVP functionality

accessible, beautiful, modular, easy to maintain and use.

### Timeline / Project

UI Core Team

**Comment by edburyenegren-okta** [comment]
@jeffbelser-okta we'd like to address some child components and library issues before moving on this, but I'm moving it into our icebox as this is a valid request.
