### ISSUE TITLE
Icons: Explore & Create

### ISSUE THREAD

**Issue by joejezowski-okta** [okta/odyssey#572]
@joejezowski-okta 
- [x] Create grid in Figma
- [x] Design list of icons
- [x] Help with page layout for icon repo
- [x] Research, refine guidelines
- [x] Create location to drop SVG's from design to dev

**Comment by joejezowski-okta** [comment]
Docs:
https://www.figma.com/file/PxtJwT1CTpUof4auvM139M/Icons?node-id=3952%3A70

Components:
https://www.figma.com/file/PxtJwT1CTpUof4auvM139M/Icons?node-id=2660%3A365

**Comment by edburyenegren-okta** [comment]
No feedback from Craft and looks :100: to me!
