### ISSUE TITLE
Tables should allow white background

### ISSUE THREAD

**Issue by mauriciocastillosilva-okta** [okta/odyssey#605]
### Summary

The page I am using the table needs white background for it, but not including the title and subtitle, just the table itself. 
Ideally also a border can be added

### MVP functionality

What functionality would be required for an initial release?
Change background color on the table
nit: allow to set surrounding border for the whole table

### Timeline / Project

Is this request related to an upcoming release or project?
This is for Recent Activity which will be EA end of August

**Comment by arnoldsandoval-okta** [comment]
@mauriciocastillosilva-okta Do you have a design that shows the use case for this? A table should inherit the background of its parent element. Any additional context you have will help us determine next steps!

Thanks!

**Comment by mauriciocastillosilva-okta** [comment]
Yes. For Recent Activity page, in end user v2, the background is gray. We want just the table to have a white background, not the title and the subtitle, we were just thinking the data table itself
Here is a screenshot

<img width="1308" alt="RecentActivity-graybg" src="https://user-images.githubusercontent.com/6979296/90572704-8f499000-e169-11ea-8beb-95e0a75a281d.png">

**Comment by edburyenegren-okta** [comment]
@mauriciocastillosilva-okta is this the Figma mock or the current implementation?

**Comment by joejezowski-okta** [comment]
@mauriciocastillosilva-okta My advice would be to have the entire page be white vs changing just the table BG. This is the visual direction we are taking Odyssey going forward. This will ensure that not only the table is on white, but at the same time providing better contrast ratio for typography on the whole page.

**Comment by mauriciocastillosilva-okta** [comment]
@joejezowski-okta: yes, we discussed changing the whole page background to white, but since this is part of enduser dashboard v2, we need to be consistent with it, and all the pages have gray background there. That would be the ideal for this page, but unfortunately it is not possible given the place where this page lives. After the last discussion we had, we decided to keep it as is, with gray background, so for the time being we are good. However as you can see, for this specific page it doesn't look great, so that is why I think it was still relevant to discuss this issue/enhacenemnt.

@edburyenegren-okta this is the actual impl. Do you need the figma? I'll find it and send it to you

**Comment by edburyenegren-okta** [comment]
@mauriciocastillosilva-okta we're going to close this issue as Odyssey won't be shipping a white background variant for Table; however, we're happy to work with Design to find alternative solutions for using these components in different scenarios.

cc @melissajones-okta @nicolasbackal-okta
