### ISSUE TITLE
Navigation Design

### ISSUE THREAD

**Issue by arnoldsandoval-okta** [okta/odyssey#612]
As part of the docs site redesign, we will need navigation.

Things to consider

- Should we group components by categories? 
  - e.g. Text Input, Checkbox, Radio Button fit under an Inputs parent? 
- Should we rename inputs for better scannability, e.g. Checkbox and Radio button become InputCheckbox and InputRadio?
- Responsive design, what happens at mobile/smaller views?

**Comment by joejezowski-okta** [comment]
https://www.figma.com/file/InD7SvjpkLshzluU22fcTq/Design-Docs?node-id=814%3A0

**Comment by joejezowski-okta** [comment]
@arnoldsandoval-okta This is what I've narrowed in on.

Here's a prototype of how the menu will work on mobile:
https://www.figma.com/proto/InD7SvjpkLshzluU22fcTq/Design-Docs?node-id=649%3A1797&viewport=3183%2C-366%2C1.3022774457931519&scaling=min-zoom
