### ISSUE TITLE
Modal not executing when clicking on the button

### ISSUE THREAD

**Issue by johnatanuribe-okta** [okta/odyssey#635]
<img width="365" alt="Screen Shot 2020-08-20 at 10 58 51 AM" src="https://user-images.githubusercontent.com/41267104/90802219-23d00180-e2d4-11ea-9ab4-617372acd2fa.png">

**Browser and version** 
Chrome 84.0.4147.125

**Steps**
Modals > Click [Let me see it already button!]

**Comment by arnoldsandoval-okta** [comment]
@edburyenegren-okta I added this to the sprint, but not the release. The PR is ready for review. I'll leave it up to you if we want to add this to the release. I recognize its sort of at the 11th hour, so I'm fine with deferring it if you feel if its the right thing to do.
