### ISSUE TITLE
Badge

### ISSUE THREAD

**Issue by johnintrater-okta** [okta/odyssey#643]
There is need for some sort of label that allows users to read explanation text when selected or link to additional info. Examples of this include: "free trial" "beta" "early access" etc. 

This was flagged by Legal (Fatima Kahn and Shailey Jain). Language in our customer contracts establishes separate terms for trial features (read: Beta, EA, pilot, preview, etc.) vs. paid features (read: GA). We need to mark these features accordingly, so customers have a clear understanding of what aspects of our service fall into this category vs. not.

There's nuance - different features present differently: the easiest is when it's a full page (e.g., dashboard), but sometimes it's something in-line or partial page.

Also, worth considering the language we use. "EA" isn't self-explanatory, and "Early Access" may still benefit from further explanation. Wouldn't hurt to explain "Beta", as well, per Okta's definition. How we do that -- tooltip? modal? -- is TBD, but should ideally be responsive and accessible.

@ericaburnett-okta, feel free to provide additional info in this ticket.

**Comment by edburyenegren-okta** [comment]
@melissajones-okta please add more color when you have more info
