### ISSUE TITLE
Additional Link Types 

### ISSUE THREAD

**Issue by johnintrater-okta** [okta/odyssey#644]
We should consider adding another link type with alternate styling including underline only on hover which can be used depending on the situation. I did my best to check out WCAG guidelines and it states, links require:

-  "A non-color indicator, such as an underline, must be present on hover
- The contrast ratio between the surrounding text and the background must be at least 4.5:1
- The contrast ratio between the link and the background must be at least 4.5:1
- The contrast ratio between the link and the surrounding text must be at least 3:1."

Reviewing other design systems, I found the following:

**Material Design**: only has "single link" style which does underline on hover only 
**Carbon**: has multiple link types. "Standalone Link" where underline is only in hover state, "Inline Link" is used in sentences or paragraphs and always styled with underline. 
**Polaris** "default link" is underline only on hover, "monochrome" and "external links" do have underline always present 
**Lightning**. all different link types have underline only shown on hover 

While it seems an argument could be made to only show underline on hover, I think having alternate link types is a better solution.

**Comment by joejezowski-okta** [comment]
Spoke with @edburyenegren-okta, decided that Grey 900 is a better option to alter. This will allow us to remove underlines on links globally while meeting WCAG 2.0 AA+ compliance. 

New Grey 900 value is to be: #1D1D21
