### ISSUE TITLE
Custom Element: Listbox

### ISSUE THREAD

**Issue by edburyenegren-okta** [okta/odyssey#653]
As we move to compose components like Multi-Select internally, we'll need a standardized Listbox. 

https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/listbox_role

**Comment by arnoldsandoval-okta** [comment]
The PR feedback I left [here](https://github.com/okta/odyssey/pull/642) provides additional context.

**Comment by edburyenegren-okta** [comment]
Duplicate of #683
