### ISSUE TITLE
Remove Warning Icon - Error Inputs

### ISSUE THREAD

**Issue by joejezowski-okta** [okta/odyssey#654]
We currently don't ship the warning icon on error'ed inputs in figma because we don't ship the icon yet. (We might not ever)

> Is this issue related to a specific component?

> What did you expect to happen? What happened instead?

> What browser & version are you experiencing this in?

## Steps to reproduce the issue

Remove the icon!

[Screen Shot 2020-09-01 at 3.46.47 PM.png](https://images.zenhubusercontent.com/5e792a89a8872810d7de1ec9/7ab449d0-6c27-4e23-ae14-6a3663f26553)

## Screenshots

Please include screenshots to help illuminate the issue.

**Comment by edburyenegren-okta** [comment]
merged into 0.5.1
