### ISSUE TITLE
Text inputs in IE 11 are not centered

### ISSUE THREAD

**Issue by santhoshbalakrishnan-okta** [okta/odyssey#660]
## Detailed description

> Is this issue related to a specific component?
Yes, but it seems like the height issue can affect other components as well.

> What did you expect to happen? What happened instead?
Expected: Text is centered in input component. 
Actual: It's more towards the bottom.

> What browser & version are you experiencing this in?
IE 11

## Steps to reproduce the issue

1. Open design docs in IE11.

## Screenshots

<img width="322" alt="Screen Shot 2020-09-09 at 10 51 10 AM" src="https://user-images.githubusercontent.com/24683447/92640918-d8858f00-f292-11ea-9ba9-f5ff03ec044b.png">

## Additional information

https://okta.slack.com/archives/C7T2H3KNJ/p1599675393024700

**Comment by edburyenegren-okta** [comment]
@santhoshbalakrishnan we're going to icebox this until we get some alignment internally on what "IE11 support" looks like (e.g. perfect parity vs visual parity vs functional parity).
