### ISSUE TITLE
Updated/New Icons for Toast

### ISSUE THREAD

**Issue by edburyenegren-okta** [okta/odyssey#684]
@joejezowski-okta could you upload the Figma exports for the latest icons here? I'll make sure they get added to the package and docs.

**Comment by joejezowski-okta** [comment]
[https://app.zenhub.com/files/183499724/eb3e9eb8-8ea9-4308-8b56-58cdf77fb7e7/download](https://app.zenhub.com/files/183499724/eb3e9eb8-8ea9-4308-8b56-58cdf77fb7e7/download)

**Comment by joejezowski-okta** [comment]
14px Icons:
[https://app.zenhub.com/files/183499724/301a9802-e6c5-4ed1-ac8f-b836c349ec81/download](https://app.zenhub.com/files/183499724/301a9802-e6c5-4ed1-ac8f-b836c349ec81/download)
