### ISSUE TITLE
Cards

### ISSUE THREAD

**Issue by joejezowski-okta** [okta/odyssey#69]
Post-hackathon steps:

visual design, additional states

data visualization design and patterns is still todo

validate with additional use cases

Lessons:

don't go down a hypothetical road, only design for use cases we know about (make an MVP)

collaboration is awesome and a big change from mostly solo work – want to do more

Accomplishments:

our team is awesome, we worked really well together without having done so much before; no one took it all over

tried to represent marketing despite having all product designers on the team – super helpful to have marketing use cases collected in advance

**Comment by edburyenegren-okta** [comment]
Dupe of https://github.com/okta/odyssey/issues/351
