### ISSUE TITLE
Inputs: Password - Replace Eyecon

### ISSUE THREAD

**Issue by joejezowski-okta** [okta/odyssey#72]
A single-line text field whose value is obscured. Use the maxlength and minlength attributes to specify the maximum length of the value that can be entered.

This ticket includes show/hide functionality for password inputs.

Reference JIRA:

https://oktainc.atlassian.net/browse/UX-1602?jql=component%20%3D%20%22Design%20System%22%20AND%20status%20!%3D%20Done

**Comment by edburyenegren-okta** [comment]
No longer applies
