### ISSUE TITLE
Re-evaluate Type Scale

### ISSUE THREAD

**Issue by joejezowski-okta** [okta/odyssey#723]
Our type scale is presenting many challenges that we saw coming. This issue is meant to log issues in order to find solutions.

**Comment by arnoldsandoval-okta** [comment]
![image.png](https://images.zenhubusercontent.com/5efa5ef3ecfd032454c7ebaf/80d50696-2869-47f2-85c9-56165aacbe73)![image.png](https://images.zenhubusercontent.com/5efa5ef3ecfd032454c7ebaf/42fc08e6-656e-495c-8193-9ae1476b12f1)

**Comment by arnoldsandoval-okta** [comment]
![image.png](https://images.zenhubusercontent.com/5efa5ef3ecfd032454c7ebaf/55ab4d9f-cc2d-48df-af04-59c99830e71d)

In this one, h2 and h3 are very similar - nearly indistinguishable from one another. Does not denote hierarchy.

**Comment by edburyenegren-okta** [comment]
https://github.com/okta/odyssey/pull/751#discussion_r516862015

<img width="974" alt="Screen Shot 2020-11-03 at 1 26 25 PM" src="https://user-images.githubusercontent.com/36284167/98042312-3d172300-1dd8-11eb-8add-3f7a16ca4439.png">

**Comment by arnoldsandoval-okta** [comment]
This one was found by @johnintrater-okta in Docs site final review. 

![image.png](https://images.zenhubusercontent.com/5efa5ef3ecfd032454c7ebaf/b6cd3afb-9e5d-449d-8376-e5623cdb9cbe)
