### ISSUE TITLE
Full width table

### ISSUE THREAD

**Issue by arnoldsandoval-okta** [okta/odyssey#725]
A request we hear very often from designers and engineers is surrounding the ability to have a full-width table. While I don't believe this is appropriate in every instance, there are times where content may run together and become hard to read. Take this for example:

![image.png](https://images.zenhubusercontent.com/5efa5ef3ecfd032454c7ebaf/e3fe1179-3893-4aa5-8932-8818dcca3ccb)

In the above screenshot, the content of the "Design", "Development" and "Documentation" columns become hard to quickly scan. By making the table full width, we can provide more space to columns, therefore improving readability.

![image.png](https://images.zenhubusercontent.com/5efa5ef3ecfd032454c7ebaf/1092b53d-e189-4461-a0e4-811b8e93c0cf)

## Proposed UAC

- Provide users an optional way to make a table full width
- Introduce variants within the component (e.g. `comfortable` vs `compact`

**Comment by edburyenegren-okta** [comment]
I think we can separate out the full-width and density solves into two tickets.
