### ISSUE TITLE
Datetime - Local

### ISSUE THREAD

**Issue by joejezowski-okta** [okta/odyssey#84]
A control for entering a date and time, with no time zone.

**Comment by johnatanuribe-okta** [comment]
@taylorlaubach-okta guidelines:
1. Make them as human-readable as possible. So like if it’s within the last year, just use month and day, not the year.
2. To keep layouts as consistent as possible, use 3 character month abbreviations.
3. To avoid ambiguity with i18n, use day month year order
So e.g. 23 Jan 2017, 23 Jan (if 2019)

**Comment by edburyenegren-okta** [comment]
@johnatanuribe-okta been about a year, but looks like those notes apply to displaying the date time itself, not the control for input.

**Comment by taylorlaubach-okta** [comment]
Yeah, that's correct. Those are for displaying the date/time. I believe they were written when I was working on the system log.
