### ISSUE TITLE
Color

### ISSUE THREAD

**Issue by joejezowski-okta** [okta/odyssey#85]
A control for specifying a color. A color picker's UI has no required features other than accepting simple colors as text.

**Comment by joejezowski-okta** [comment]
@edburyenegren-okta is this a request for a color picker UI? This issue derives from JIRA.

**Comment by edburyenegren-okta** [comment]
@joejezowski-okta yup: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/color
