### ISSUE TITLE
Patterns: object list versus data table

### ISSUE THREAD

**Issue by joejezowski-okta** [okta/odyssey#91]
Conversation:

Alex Dahl
June 21, 2018, 12:36 PM

I have a hunch we should split our data list pattern into two separate components – one for a list of objects (groups, people, policies, etc) and another for tabular data (reports?).

Edbury Enegren
June 21, 2018, 1:23 PM

Alex Dahl do you know who might have some historical context on "Data List"? 

It's a weird pattern to have considering we don't have any table styling.

Alex Dahl
June 21, 2018, 1:50 PM

Edbury Enegren, not specifically... old guard of Brian and Shawn could probably help.

Yeah, it's obviously a valuable pattern because we use a ton of data lists – probably too many, it's stretched in weird ways sometimes – but I don't know its story.

Edbury Enegren
June 21, 2018, 3:18 PM

Whatever the context for its creation, I think you're on the money that having a straightforward Table component might ease up on some DataList use. There are a lot of cases where it's too robust.

**Comment by edburyenegren-okta** [comment]
Closing this as it refers mainly to Admin patterns and their broad use, not Odyssey patterns. DataList should be replaced with Table and a List component is upcoming.
