### ISSUE TITLE
Figma Kit link is broken on odyssey.okta.design

### ISSUE THREAD

**Issue by subimage** [okta/odyssey#915]
## Detailed description

I'm trying to access the Figma kit from https://odyssey.okta.design/ …when I click on the "Figma Kit" link, it opens Figma; but no file is found. When I search Figma community there's also no file.

Really interested to check this out! 

## Steps to reproduce the issue

1. Visit https://odyssey.okta.design/
2. Click the "Figma Kit" link (https://www.figma.com/files/676870123940302956/project/2512934/Odyssey-UI)
3. The link opens Figma.com, but no UI kit is available…it just goes to my personal dashboard.

## Screenshots

Please include screenshots to help illuminate the issue.

**Comment by edburyenegren-okta** [comment]
Hiya @subimage  

Sadly, our Figma kit isn't publicly available yet - we'll be adding that note to our documentation. Apologies for any confusion!
