### ISSUE TITLE
Provide tokens for font weights (feature request)

### ISSUE THREAD

**Issue by alexdahl-okta** [okta/odyssey#94]
The design system currently requires components to specify font weights by exact numeric value (`300`, `400`, `600`).

This is fragile:
- If the exact values the system uses change in the future, all components will have to be updated.
- If a theme uses different weights or fonts, the exact values need to be overridden for all components.
- If a designer or developer does not remember the exact values, they may specify or implement an incorrect weight.

The system should define variables for the weights it requires: lighter, normal, and bolder.

- [Carbon provides](https://github.com/carbon-design-system/carbon/blob/master/packages/type/src/fontWeight.js) `light`, `regular`, and `semibold` abstracts, so that components can declare weights such as `font-weight: carbon--font-weight('light')`.
- [Lightning provides](https://lightningdesignsystem.com/design-tokens/#category-font) `$font-weight-bold`, `$font-weight-light`, and `$font-weight-regular` tokens.

**Comment by edburyenegren-okta** [comment]
@arnoldsandoval-okta this feels like a straightforward token to add. thoughts on getting this into the initial set?
