### ISSUE TITLE
Shadows 

### ISSUE THREAD

**Issue by alexdahl-okta** [okta/odyssey#95]
The design system currently requires components to completely specify box shadows on their own.

For example: [clickable cards](https://github.com/okta/odyssey/blob/master/src/scss/components/_card.scss#L144) (with default and hover styles), [dropdowns](https://github.com/okta/odyssey/blob/master/src/scss/components/_dropdown.scss#L40), and toasts.

As more components start to use shadow and elevation to communicate specific meaning, the system should provide a consistent solution. Our initial need is probably default and hover for interactive objects, and an elevation layer for non-interactive components. There may be future needs, such as drag and drop states.

- Within Odyssey, [$border-default](https://github.com/okta/odyssey/blob/master/src/scss/abstracts/_variables.scss#L47) is a good prototype.
- [Lightning provides](https://lightningdesignsystem.com/design-tokens/#category-shadow) a few tokens:`$shadow-drag`, `$shadow-drop-down`, and `$shadow-header`.

**Comment by nickarcidy-okta** [comment]
Current work on shadow logic can be found here:
https://www.figma.com/file/17arx4uP1ol9BL9g2N2jS3/Shadow-logic?node-id=0%3A1

**Comment by joejezowski-okta** [comment]
Thanks Nick!

@nickarcidy-okta @edburyenegren-okta @johnintrater-okta 

I have some concerns about working on this right now. Although it may seem like this is a simple build (which it is), I'm thinking that we don't have enough components in place to audit our needs for them. We can make assumptions, but realistically the only UI that we have in our system now that could benefit from a shadow is a modal. If we build this now, our thoughts can easily change for net new UI's. I can assume that we might want our modal shadow to be different from a card shadow. For these reasons, I see this lower on the priority scale. Thoughts?

**Comment by johnintrater-okta** [comment]
@joejezowski-okta that is a really good point. I totally buy that as a good reason to push this out a bit.

**Comment by edburyenegren-okta** [comment]
Ref: https://github.com/okta/odyssey/pull/700#discussion_r498534220
